---
prerun: false
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ../default/settings/$PLAYBOOK.yml
  playbooks:
    prepare: ../default/prepare/$PLAYBOOK.yml
    converge: ../default/converge/$PLAYBOOK.yml
    verify: ../default/verify/$PLAYBOOK.yml
  env:
    ANSIBLE_CALLBACK_PLUGINS: $MOLECULE_PROJECT_DIRECTORY/plugins/callback
    ANSIBLE_STRATEGY_PLUGINS: $HOME/.ansible/venv/site-packages/ansible_mitogen/plugins/strategy
  config_options:
    defaults:
      strategy: ${ANSIBLE_STRATEGY:-mitogen_linear}
      stdout_callback: ${ANSIBLE_STDOUT_CALLBACK:-unixy2}
      verbosity: 1
dependency:
  name: shell
  command: ansible-galaxy install -r molecule/default/requirements.yml
lint: |
  ansible-lint
scenario:
  test_sequence:
    - dependency
    - syntax
    - lint
    # destroy
    # create
    - prepare
    - converge
    - idempotence
    - verify
    # destroy
  create_sequence:
    - create
    # prepare
  destroy_sequence:
    - destroy
    # cleanup
  converge_sequence:
    - converge
verifier:
  name: ansible
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
    groups:
      - local_molecule
...
