---
## handlers for ivansible.linux.wireguard

- name: remove wireguard-go build directory
  ansible.builtin.file:
    path: "{{ wireguard_go_build_dir.path }}"
    state: absent
  become: true

- name: remove wireguard-go build cache
  ansible.builtin.file:
    path: ~/.cache/go-build
    state: absent
  become: true

- name: restart wireguard service
  ansible.builtin.systemd:
    name: "wg-quick@wg{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
  loop: "{{ range(lin_wg_nets |count) |list }}"
  loop_control:
    label: "wg{{ item }}"
...
