---
## defaults for ivansible.lin_docker

is_permitted: false
docker_permit_user: false

docker_from_docker_io: "{{ ansible_lsb.release is version('20.04','<') or docker_focal_fix |bool }}"
docker_focal_fix: true

docker_upgrade: false
docker_extras: false
## bash completion scripts for docker-compose and docker-machine
docker_bash_completion_extras: false

docker_compose_github_enable: "{{ docker_from_docker_io }}"
docker_compose_release: latest
docker_compose_binary_file: /usr/local/bin/docker-compose

docker_machine_github_enable: false
docker_machine_release: latest
docker_machine_binary_file: /usr/local/bin/docker-machine

docker_hub_username: ""
docker_hub_password: ""

docker_files_repo: ""
docker_files_branch: master
docker_files_dir: ~/devel/docker

docker_bash_aliases:
  dc: docker-compose
  dr: docker
  drd: docker stack deploy
  drf: docker system df
  drl: docker ps -lq
  drp: docker system prune -f
  drk: docker stack
  drs: docker service
  drtop: docker container stats

docker_daily_gc: "{{ docker_swarm_role |default('none',true) != 'none' }}"

## daemon tls settings
docker_tls_enable: false
docker_tls_reset: false
docker_tls_addr: 127.0.0.1

docker_tls_params:
  type: ECC
  curve: secp256r1
  size: 256
  days: +3650d
  ca_days: +3650d

docker_tls_ca_crt: ~  # predefined CA crt text (default: generate)
docker_tls_ca_key: ~  # predefined CA key text (default: generate)
docker_tls_ca_cname: ca.example.com

docker_tls_server_crt: ~  # predefined server crt text (default: generate)
docker_tls_server_key: ~  # predefined server key text (default: generate)
docker_tls_server_cnames: dockerd.example.com

docker_tls_client_cname: docker-cli.example.com

## docker swarm settings
## role: worker, manager-worker, manager-only, manager-master, none
docker_swarm_role: none

docker_swarm_manager_ip: "{{ ansible_default_ipv4.address }}"
docker_swarm_manager_port: 2377

docker_swarm_ports:
  - 2376/tcp  # daemon tls
  - 2377/tcp  # swarm manager
  - 7946/any  # intra-node
  - 4789/udp  # overlay net (vxlan)

docker_swarm_ram_threshold_mb: 984

## overriding custom daemon settings
## 'none' and '' values are ignored
## '-' values will be removed
## labels should be provided as a map
docker_daemon_user_settings: {}
docker_daemon_user_labels: {}
docker_daemon_reset: false
docker_daemon_backup: false

## docker network settings
docker_listen_sockets:
  - "unix:///var/run/docker.sock"
  - "{{ docker_tls_enable |bool |ternary('tcp://%s:2376' % docker_tls_addr, none) }}"

docker_bridge_pool4: ~    # 172.16.0.0/12
docker_bridge_addr4: ~    # 172.17.0.1/16
docker_bridge_subnet6: ~  # fdff:dead:beef::/64
docker_enable_ipv6: ~

docker_gwbridge_addr4: ~      # 172.18.0.1/16
docker_gwbridge_force: false  # true will leave swarm to update gwbridge

docker_swarm_overlay_pool4: ~    # 10.0.0.0/8
docker_swarm_ingress_subnet4: ~  # 10.255.0.0/16
docker_swarm_ingress_encrypt: ~

## docker daemon settings
docker_daemon_log_level: ~  # warn
docker_storage_driver: ~  # overlay2
docker_daemon_use_criu: ~
docker_daemon_proxy: ~

docker_miss_containerd: "{{ lookup('env', 'TRAVIS') |bool and
                            ansible_connection == 'local' }}"
docker_containerd_sock: "{{ docker_miss_containerd |bool
                          | ternary(none, '/run/containerd/containerd.sock') }}"

docker_daemon_base_settings:
  log-level: "{{ docker_daemon_log_level }}"
  containerd: "{{ docker_containerd_sock }}"
  storage-driver: "{{ docker_storage_driver }}"

  hosts: "{{ docker_listen_sockets |d([],true) |select |list }}"

  tls: "{{ docker_tls_enable |bool |ternary(true, '-') }}"
  tlsverify: "{{ docker_tls_enable |bool |ternary(true, '-') }}"
  tlscacert: "{{ docker_tls_enable |bool |ternary('/etc/docker/ca.crt', '') }}"
  tlscert: "{{ docker_tls_enable |bool |ternary('/etc/docker/server.crt', '') }}"
  tlskey: "{{ docker_tls_enable |bool |ternary('/etc/docker/server.key', '') }}"

  ipv6: "{{ none if (docker_enable_ipv6 is none)
            else docker_enable_ipv6 |bool }}"
  fixed-cidr-v6: "{{ docker_enable_ipv6 |bool |ternary(docker_bridge_subnet6, '-') }}"
  bip: "{{ docker_bridge_addr4 }}"
  default-address-pools: "{{ none if (docker_bridge_pool4 is none) else
                             '-' if (docker_bridge_pool4 == '-') else
                             [{'base': docker_bridge_pool4, 'size': 24}] }}"

  experimental: "{{ none if (docker_daemon_use_criu is none)
                    else docker_daemon_use_criu |bool }}"
  live-restore: ~  # live restore is incompatible with swarm mode

## dynamic docker engine labels
docker_daemon_base_labels:
  os.family: "{{ ansible_lsb.id |lower }}"
  os.codename: "{{ ansible_lsb.codename }}"
  os.arch: "{{ ansible_architecture }}"

  os.cpus: "{{ ansible_processor_count }}"
  os.memory.gb: "{{ (ansible_memtotal_mb / 1024) |round(1)
                    if ansible_memtotal_mb < 1000 else
                    (ansible_memtotal_mb + 127) // 1024 }}"
  os.memory.mb: "{{ ansible_memtotal_mb }}"
...
