---
- name: detect latest rclone release
  github_release:
    repository: rclone
    release: "{{ lin_rclone_version }}"
    owner: "{{ lin_rclone_repo_owner }}"
    template: "{download_url}/rclone-{ver}-linux-{goarch}.deb"
    version_script: "{{ lin_rclone_binary }} version"
    reinstall: "{{ lin_rclone_upgrade |bool }}"
  tags: skip_ansible_lint
  register: _rclone_release

- name: install rclone package
  apt:
    deb: "{{ _rclone_release.url }}"
    only_upgrade: "{{ not lin_rclone_upgrade |bool }}"
  register: _rclone_deb
  failed_when:
    - _rclone_deb.failed
    - _rclone_deb.msg is not search('later version is already installed')
  when: _rclone_release is changed
  notify: restart remote systemd mounts

- name: generate rclone bash completion
  command: "{{ lin_rclone_binary }} genautocomplete bash"
  when: _rclone_release is changed
...
