---
- name: refresh host facts as non-root
  setup:
  become: no
  tags: lin_rclone_all

- name: run rclone tasks as root
  import_tasks: root.yml
  become: yes
  tags: lin_rclone_all

- name: reload systemd mounts now
  meta: flush_handlers
  tags: lin_rclone_all
...
