---
- name: configure ferm port forwards
  ivansible.base.ferm_rule:
    name: forwards
    prio: 76
    rule: "{{ lookup('template', 'forwards.ferm') }}"
  tags: skip_ansible_lint

- name: disable ufw port forwarding (skip in check mode; please ignore possible failure)
  ansible.builtin.systemd:
    name: ufw-forwards
    state: stopped
    enabled: false
  failed_when: false
  no_log: "{{ hide_secrets |bool }}"
  ## this task always reports as changed in check mode
  when: not ansible_check_mode
...
