---
- name: install mosh
  ansible.builtin.apt:
    name: mosh

- name: open mosh ports in ferm
  ivansible.base.ferm_port:
    port: "{{  lin_mosh_ports }}"
    proto: udp
    comment: mosh
  when: lin_firewall == 'ferm'
  tags:
    - skip_ansible_lint
    - lin_bastion_firewall

- name: open mosh ports in ufw
  community.general.ufw:
    port: "{{ lin_mosh_ports }}"
    proto: udp
    rule: allow
  when: lin_firewall == 'ufw'
  tags: lin_bastion_firewall

- name: install mosh helper for mobaxterm
  ansible.builtin.copy:
    src: mosh-server-moba.sh
    dest: /usr/local/bin/mosh-server-moba
    mode: 0755
  tags: lin_bastion_mobaxterm
...
