---
# defaults for ivansible.lin_rsyslog

lin_rsyslog_max_journal: 200M

lin_rsyslog_keenetic_ip: ""

lin_rsyslog_separate_ufw: false
lin_rsyslog_separate_drupal: false
lin_rsyslog_separate_cron: false

lin_rsyslog_thin_php_cleaner: false

lin_rsyslog_force_rules: false

lin_rsyslog_remote_enable: true
...
