---
# defaults file for ivansible.lin_core

lin_core_system_locale: ''

lin_core_timezone: ''

lin_core_sysctl: {}

lin_core_time_sync: true
lin_core_open_ntp: false
lin_core_resync_once: false
lin_core_resync_onboot: false
lin_core_resync_services: [nginx, sslh, docker]  # services that need precise time
lin_core_time_server: 2.pool.ntp.org  # note: supports both ipv4/ipv6

lin_cron_adjust: false
lin_cron_timers:
  hourly: hourly
  daily: daily
  weekly: weekly
  monthly: monthly

lin_core_swap_enable: false
lin_core_swap_mb: 0
lin_core_swap_file: /swapfile

# https://askubuntu.com/questions/1357/how-to-empty-swap-if-there-is-free-ram
lin_core_vm_swappiness: 10
lin_core_vm_cache_presure: 50

lin_core_apt_disable_32bit: false
lin_core_apt_fast_mirrors: false

lin_core_apt_allow_universe: true
lin_core_apt_allow_src: true
lin_core_apt_allow_backports: true

lin_core_hide_changes: true

lin_core_packages_core:
  - systemd
  - systemd-cron
  - ntp
  - ntpdate
  # timedatectl requires dbus, see https://askubuntu.com/a/1015391
  - dbus
  # /usr/bin/file is missing on bionic, required by openvpn install
  - file
  # system core
  - openssh-server
  - openssh-client
  # support for en_US.UTF-8
  - locales
  # getfacl, setfacl
  - acl
  # network
  - ifupdown
  - iproute2
  - iputils-ping
  - bridge-utils
  - traceroute
  - dnsutils
  - bind9-host
  - curl
  - wget
  - netcat
  - iperf
  - ufw
  - rsync
  # utilities
  - "{{ 'gpg' if ansible_lsb.codename != 'xenial' else 'gnupg' }}"
  - at
  - git
  - vim
  - gzip
  - unzip
  - dwdiff
  - tmux
  - ncdu

lin_core_packages_devel:
  # packaging
  - aptitude
  - apt-file
  - apt-transport-https
  - software-properties-common
  - "{{ lin_use_python2 |bool |ternary('python-apt', '') }}"
  - python3-apt
  # development
  - python
  - python3
  - "{{ lin_use_python2 |bool |ternary('python-pip', '') }}"
  - python3-pip
  - virtualenv
  - build-essential
  - bash-completion
...
