---
- name: become root and apply syslog settings
  ansible.builtin.import_tasks: root.yml
  become: true
  when: lin_use_rsyslog |bool
  tags: lin_rsyslog_all

- name: flush handlers
  ansible.builtin.meta: flush_handlers
  tags: lin_rsyslog_all
...
