---
- name: install ifupdown package
  ansible.builtin.apt:
    name: ifupdown
    state: present

- name: ensure include directory for interfaces
  ansible.builtin.file:
    path: /etc/network/interfaces.d
    state: directory
    mode: 0755

- name: ensure includes in interfaces
  ansible.builtin.lineinfile:
    path: "/etc/network/{{ item }}"
    line: 'source /etc/network/interfaces.d/*'
    regexp: '^source(-directory)? /etc/network/interfaces\.d'
    insertbefore: '^auto |^#VAGRANT-|^\s*$'
    firstmatch: true
    create: true
    mode: 0644
  loop: "{{ lin_net_interfaces_files }}"
...
