---
namespace: ivansible
name: linux
version: 1.0.0

description: Ansible collection for Linux roles

authors:
  - Ivan Andreev <ivandeex@gmail.com>

tags:
  - linux
  - ansible
  - docker
  - rclone
  - restic
  - ferm
  - firewall
  - network
  - vpn
  - openvpn
  - wireguard
  - yggdrasil

# https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification
# namespace.name: version_range
dependencies: {}

repository: https://github.com/ivansible/linux
documentation: https://github.com/ivansible/linux
homepage: https://github.com/ivansible/linux
issues: https://github.com/ivansible/linux/issues

readme: README.md
license: MIT

build_ignore:
  - '*.pyc'
  - '*.tar'
...
