---
## handlers for ivansible.lin_net

- name: restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: true
  become: true

- name: restart ntp daemon
  ansible.builtin.systemd:
    name: ntp
    state: restarted
  become: true
  failed_when: false
...
