---
## handlers for ivansible.lin_bastion

- name: restart ufw forwards
  ansible.builtin.systemd:
    name: ufw-forwards
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
...
