---
- name: install wireguard as root
  import_tasks: root.yml
  become: true
  when: lin_wg_nets |default([])
  tags:
    - lin_wg_all
    - lin_wireguard_all

- name: run wireguard handlers
  meta: flush_handlers
  tags:
    - lin_wg_all
    - lin_wireguard_all
...
