---
- name: install ferm
  ansible.builtin.include_tasks: install.yml
  args:
    apply:
      become: true
      tags:
        - lin_ferm_install
        - lin_ferm_all
  when: ferm_install |bool
  tags:
    - lin_ferm_install
    - lin_ferm_all

- name: configure ferm
  ansible.builtin.include_tasks: config.yml
  args:
    apply:
      become: true
      tags:
        - lin_ferm_config
        - lin_ferm_all
  when: ferm_install |bool
  tags:
    - lin_ferm_config
    - lin_ferm_all

- name: run ferm service
  ansible.builtin.include_tasks: service.yml
  args:
    apply:
      become: true
      tags:
        - lin_ferm_service
        - lin_ferm_all
  when: ferm_install |bool
  tags:
    - lin_ferm_service
    - lin_ferm_all

- name: start ferm before setting rules
  ansible.builtin.meta: flush_handlers
  tags:
    - lin_ferm_all

- name: setup ferm rules
  ansible.builtin.include_tasks: rules.yml
  args:
    apply:
      become: true
      tags:
        - lin_ferm_rules
        - lin_ferm_all
  when: ferm_install |bool
  tags:
    - lin_ferm_rules
    - lin_ferm_hosts
    - lin_ferm_all
...
