---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
    groups:
      - molecule
provisioner:
  name: ansible
  inventory:
    group_vars:
      molecule:
        linbase_system_locale: en_US.UTF-8
        linbase_time_sync: true
        allow_sysctl: false
        lin_use_firewall: ${IVATEST_FIREWALL:-true}
        lin_use_ssh: ${IVATEST_SSH_PORT:-true}      # port 0 casts as false, otherwise true
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/playbook.yml
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      max-line-length: 120
  directory:
    ../default/tests
lint:
  name: yamllint
  options:
    config-file: .yamllint.yml
scenario:
  name: localhost
  test_sequence:
    - lint
    - dependency
    # - cleanup
    # - destroy
    - syntax
    # - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    # - cleanup
    # - destroy
...
