---
- name: setup cloudflare cname for nginx sni upstream
  community.general.cloudflare_dns:
    account_email: "{{ ygg_cf_email }}"
    account_api_token: "{{ ygg_cf_token }}"
    zone: "{{ zone }}"
    record: "{{ name }}"
    type: CNAME
    value: "{{ ygg_nginx_cname }}"
    ## yggdrasil tls behind cloudflare failed with "tls not exactly 1 cert"
    proxied: false
  delegate_to: localhost
  vars:
    fqdn: "{{ ygg_nginx_host }}"
    name: "{{ fqdn |regex_replace('^([^.]+)[.](.*)$', '\\1') }}"
    zone: "{{ fqdn |regex_replace('^([^.]+)[.](.*)$', '\\2') }}"
  when:
    - ygg_nginx_host |d('')
    - ygg_nginx_cname |d('')
  tags: lin_ygg_nginx

- name: update yggdrasil ipv6 in cloudflare
  community.general.cloudflare_dns:
    account_email: "{{ ygg_cf_email }}"
    account_api_token: "{{ ygg_cf_token }}"
    zone: "{{ ygg_cf_zone }}"
    record: "{{ alias }}{{ suffix }}"
    type: AAAA
    value: "{{ ipv6 }}"
    proxied: false
    state: present
    solo: true
  become: false
  delegate_to: localhost
  register: cloudflare_result
  until: cloudflare_result is successful
  vars:
    name: "{{ inventory_hostname }}"
    alias: "{{ ygg_alias |d(name, true) }}"
    suffix: "{{ ygg_cf_suffix |d('',true) }}"
    ipv6: "{{ ygg_ipv6 |d('') }}"
  when: ipv6 |d('')

- name: update yggdrasil ipv6 for connected peers in cloudflare
  community.general.cloudflare_dns:
    account_email: "{{ ygg_cf_email }}"
    account_api_token: "{{ ygg_cf_token }}"
    zone: "{{ ygg_cf_zone }}"
    record: "{{ alias }}{{ suffix }}"
    type: AAAA
    value: "{{ ipv6 }}"
    proxied: false
    state: present
    solo: true
  become: false
  delegate_to: localhost
  register: cloudflare_result
  until: cloudflare_result is successful
  vars:
    name: "{{ item }}"
    peer: "{{ hostvars[item] }}"
    alias: "{{ peer.ygg_alias |d(name, true) }}"
    suffix: "{{ peer.ygg_cf_suffix |d('',true) }}"
    ipv6: "{{ peer.ygg_ipv6 |d('') }}"
  when: ipv6 |d('')
  loop: "{{ ygg_slave_peers |d([],true) }}"
  loop_control:
    label: "{{ alias }}"
...
