---
- name: setup yggdrasil on linux as root
  ansible.builtin.import_tasks: root.yml
  become: true
  when: ygg_enable |bool
  tags:
    - lin_ygg_all
    - lin_yggdrasil_all

- name: restart yggdrasil service if needed
  ansible.builtin.meta: flush_handlers
  tags:
    - lin_ygg_all
    - lin_yggdrasil_all

- name: update yggdrasil ipv6 in dns
  ansible.builtin.import_tasks: dns.yml
  when: ygg_cf_enable |bool
  tags:
    - lin_ygg_dns
    - lin_ygg_cloudflare
    - lin_ygg_all
    - lin_yggdrasil_all

- name: see if yggdrasil helpers should be installed
  ansible.builtin.stat:
    path: "{{ ygg_peer_database }}"
  register: _ygg_db_file
  when: is_permitted |d(false) |bool
  tags:
    - lin_ygg_user
    - lin_ygg_all
    - lin_yggdrasil_all

- name: install yggdrasil user helpers
  ansible.builtin.include_tasks: user.yml
  args:
    apply:
      become: false
      tags:
        - lin_ygg_user
        - lin_ygg_all
        - lin_yggdrasil_all
  when:
    - ygg_update_db |bool
    - _ygg_db_file.stat.exists |d(false) |bool
  tags:
    - lin_ygg_user
    - lin_ygg_all
    - lin_yggdrasil_all
...
