---
- name: setup yggdrasil on linux as root
  import_tasks: root.yml
  become: true
  when: ygg_enable |bool
  tags:
    - lin_ygg_all
    - lin_yggdrasil_all

- name: restart yggdrasil service if needed
  meta: flush_handlers
  tags:
    - lin_ygg_all
    - lin_yggdrasil_all

- name: update yggdrasil ipv6 in dns
  import_tasks: dns.yml
  when: ygg_cf_enable |bool
  tags:
    - lin_ygg_dns
    - lin_ygg_cloudflare
    - lin_ygg_all
    - lin_yggdrasil_all
...
