---
- name: create group for proxy processes incl. yggdrasil
  ansible.builtin.group:
    name: proxy
    gid: 13
  when: ygg_unix_group == 'proxy'
  tags:
    - lin_ygg_install
    - lin_ygg_config
    - lin_ygg_service

- name: install yggdrasil
  ansible.builtin.import_tasks: install.yml
  tags: lin_ygg_install

- name: configure yggdrasil
  ansible.builtin.import_tasks: config.yml
  tags: lin_ygg_config

- name: setup firewall for yggdrasil
  ansible.builtin.import_tasks: firewall.yml
  tags: lin_ygg_firewall

- name: setup yggdrasil service
  ansible.builtin.import_tasks: service.yml
  tags: lin_ygg_service

- name: setup nginx sni upstream for yggdrasil
  ansible.builtin.include_role:
    name: ivansible.base.nginx
    tasks_from: setup_sni_upstream.yml
  vars:
    facility: yggdrasil
    hostname: "{{ ygg_nginx_host |d('') }}"
    port: "{{ ygg_tls_port |int }}"
  when:
    - ygg_tls_port |d(0) |int
  tags: lin_ygg_nginx
...
