---
- name: fix error "storage.googleapis.com/bazel-apt key expired"
  apt_key:
    url: https://bazel.build/bazel-release.pub.gpg
  when: ansible_virtualization_type != 'docker'
  ## task requires gpg which is not always present on a pristine system
  failed_when: false

- name: use local apt mirrors
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    backup: true
    mode: 0644
  register: apt_switch_mirrors
  when: lin_core_apt_fast_mirrors |bool

- name: disable 32-bit apt repositories
  replace:
    path: /etc/apt/sources.list
    regexp: '^\s*deb\s+http'
    replace: 'deb [arch=amd64] http'
    backup: true
  register: apt_disable_32bit
  when:
    - lin_core_apt_disable_32bit |bool
    - lin_apt_arch == 'amd64'

- name: update apt caches
  apt:
    update_cache: true
  when: apt_switch_mirrors is changed
        or apt_disable_32bit is changed
  ## retry on error occurring when a fresh server is warming up from snapshot:
  ## "Failed to lock apt for exclusive operation"
  register: _first_apt_update
  until: _first_apt_update.msg |default('') is not search('Failed to lock apt')
  retries: 29
...
