---
- name: detect ssh port
  set_fact:
    real_ssh_port: "{{ real_ssh_port
                     | default(ansible_port)
                     | default(ansible_ssh_port)
                     | default(22) }}"

- name: open ssh port
  ufw:
    rule: allow
    port: "{{ real_ssh_port }}"
    proto: tcp
  no_log: true

- name: close port 22/tcp, if not used
  ufw:
    rule: allow
    port: "22"
    proto: tcp
    delete: yes
  no_log: true
  when: real_ssh_port|int != 22

- name: close port 22 (tcp or udp), if not used
  ufw:
    rule: allow
    port: "22"
    delete: yes
  no_log: true
  when: real_ssh_port|int != 22

- name: open ntp port
  ufw:
    rule: allow
    port: "123"
    proto: udp
  no_log: true

- name: enable ubuntu firewall
  ufw:
    state: enabled
  no_log: true

- name: test connection
  ping:
...
