---
- name: tune kernel parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/77-system.conf
  with_dict: "{{ lin_core_sysctl }}"
  loop_control:
    label: "{{ item.key | regex_replace('^net\\.') }}"


- name: set vm swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ lin_core_vm_swappiness |string }}"
    state: present
    sysctl_file: /etc/sysctl.d/77-vm.conf
  when:
    - lin_core_vm_swappiness |d('')
    - lin_core_swap_enable |bool
  tags: lin_core_swap

- name: set vm cache pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ lin_core_vm_cache_presure |string }}"
    state: present
    sysctl_file: /etc/sysctl.d/77-vm.conf
  when:
    - lin_core_vm_cache_presure |d('')
    - lin_core_swap_enable |bool
  tags: lin_core_swap


- name: enable BBR TCP congestion control on modern kernels
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.val }}"
    state: present
    sysctl_file: /etc/sysctl.d/77-bbr.conf
  loop:
    - key: net.core.default_qdisc
      val: fq
    - key: net.ipv4.tcp_congestion_control
      val: bbr
  loop_control:
    label: "{{ item.key | regex_replace('^net\\.') }}"
  when: ansible_kernel is version('4.9', '>')
  tags: lin_core_bbr
...
