---
- name: detect ngrok download location
  uri:
    url: https://ngrok.com/download
    return_content: yes
    creates: /usr/local/bin/ngrok
  #connection: local  # never use this with "creates"
  register: ngrok_download_html
  when: "ngrok_zip_url == 'latest'"

- name: extract ngrok download location
  set_fact:
    ngrok_zip_url:
      "{{ ngrok_download_html.content
        | regex_search('https://[^\"]+ngrok-stable-linux-amd64.zip') }}"
  when: "'content' in ngrok_download_html"

- name: install ngrok
  unarchive:
    src: "{{ ngrok_zip_url }}"
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/ngrok
...
