---
- name: remove requiretty from sudoers
  lineinfile:
    path: /etc/sudoers
    regexp: '^(Defaults\s+requiretty.*)'
    state: absent
    backup: true
  tags: linsys_settings


- name: switch to fast apt mirrors
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    backup: true
  register: apt_switch_mirrors
  when: linsys_apt_fast_mirrors |bool
  tags: linsys_mirrors

- name: update apt caches
  apt:
    update_cache: true
  when: apt_switch_mirrors is changed
  tags: linsys_mirrors


- name: fix localectl problem in minimal xenial docker
  # systemd-localed service cannot start without /etc/default/keyboard on xenial
  # see: https://github.com/systemd/systemd/issues/911
  copy:
    dest: /etc/default/keyboard
    content: ""
    force: false
  when: ansible_lsb.codename == 'xenial'
  tags: linsys_settings

- name: set system locale
  command: >
    localectl set-locale
      LANG={{ linsys_system_locale }}
      LANGUAGE={{ linsys_system_locale }}
  changed_when: not linsys_hide_changes |bool
  when: linsys_system_locale != '' # noqa 602
  tags: linsys_settings

- name: set timezone
  timezone:
    name: "{{ linsys_timezone }}"
  when: linsys_timezone != '' # noqa 602
  tags: linsys_settings


- block:
    - name: install core packages (ok to fail once, output hidden)
      apt:
        name: "{{ linsys_packages_core }}"
        state: present
      # failure message is too verbose, silence by default
      no_log: "{{ hide_secrets |bool }}"
  rescue:
    - name: update apt cache and install core packages
      apt:
        name: "{{ linsys_packages_core }}"
        state: present
        update_cache: true
  tags: linsys_packages

- name: install core development packages
  apt:
    name: "{{ linsys_packages_devel }}"
    state: present
  tags: linsys_packages

# it may be a good idea to restart mitogen runner
# after installing python apt bindings
#- meta: reset_connection


- name: synchronize system time
  # this task requires time packages, which are installed above
  import_tasks: timesync.yml
  when: linsys_time_sync |bool
  tags: linsys_timesync


- name: disable telemetry on ubuntu bionic
  import_tasks: telemetry.yml
  when: ansible_lsb.codename == 'bionic'
  tags: linsys_telemetry


- name: tune kernel parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/77-system.conf
  with_dict: "{{ linsys_sysctl }}"
  loop_control:
    label: "{{ item.key | regex_replace('^net\\.') }}"
  when: allow_sysctl |bool
  tags: linsys_sysctl

- name: enable BBR TCP congestion control on modern kernels
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.val }}"
    state: present
    sysctl_file: /etc/sysctl.d/77-bbr.conf
  loop:
    - key: net.core.default_qdisc
      val: fq
    - key: net.ipv4.tcp_congestion_control
      val: bbr
  loop_control:
    label: "{{ item.key | regex_replace('^net\\.') }}"
  when: ansible_kernel is version('4.9', '>')
        and allow_sysctl |bool
  tags:
    - linsys_sysctl
    - linsys_bbr


- name: setup swap space
  import_tasks: swap.yml
  when: linsys_swap_enable |bool
        and linsys_swap_mb |int > 0
  tags: linsys_swap


- name: derive ssh port
  set_fact:
    real_ssh_port: "{{ real_ssh_port
                     | default(ansible_port)
                     | default(ansible_ssh_port)
                     | default(22) }}"
  tags:
    - linsys_ssh
    - linsys_firewall

- name: configure port for ssh service
  import_tasks: ssh.yml
  when: lin_use_ssh |bool
  tags: linsys_ssh

- name: activate firewall
  import_tasks: firewall.yml
  when: lin_use_firewall |bool
  tags: linsys_firewall
...
