---
- name: remove requiretty from sudoers
  lineinfile:
    path: /etc/sudoers
    regexp: '^(Defaults\s+requiretty.*)'
    state: absent
    backup: yes
  tags: linbase_settings


- name: switch to fast apt mirrors
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    backup: yes
  register: apt_switch_mirrors
  when: linbase_apt_fast_mirrors |bool
  tags: linbase_mirrors

- name: update apt caches
  apt:
    update_cache: yes
  when: apt_switch_mirrors is changed
  tags: linbase_mirrors


- name: fix localectl problem in minimal xenial docker
  # systemd-localed service cannot start without /etc/default/keyboard on xenial
  # see: https://github.com/systemd/systemd/issues/911
  copy:
    dest: /etc/default/keyboard
    content: ""
    force: no
  when: ansible_lsb.codename == 'xenial'
  tags: linbase_settings

- name: set system locale
  command: >
    localectl set-locale
      LANG={{ linbase_system_locale }}
      LANGUAGE={{ linbase_system_locale }}
  changed_when: not linbase_hide_changes |bool
  when: linbase_system_locale != '' # noqa 602
  tags: linbase_settings

- name: set timezone
  timezone:
    name: "{{ linbase_timezone }}"
  when: linbase_timezone != '' # noqa 602
  tags: linbase_settings


- block:
    - name: install core packages (ok to fail once, output hidden)
      apt:
        name: "{{ linbase_packages_core }}"
        state: present
      # failure message is too verbose, silence by default
      no_log: "{{ hide_secrets |bool }}"
  rescue:
    - name: update apt cache and install core packages
      apt:
        name: "{{ linbase_packages_core }}"
        state: present
        update_cache: yes
  tags: linbase_packages

- name: install development packages
  apt:
    name: "{{ linbase_packages_devel }}"
    state: present
  tags: linbase_packages

# it may be a good idea to restart mitogen runner
# after installing python apt bindings
#- meta: reset_connection


- name: synchronize system time
  # this task requires time packages, which are installed above
  import_tasks: timesync.yml
  when: linbase_time_sync |bool
  tags: linbase_timesync


- name: disable telemetric on bionic
  import_tasks: telemetry.yml
  when: ansible_lsb.codename == 'bionic'
  tags: linbase_telemetry


- name: install golang
  import_tasks: golang.yml
  when: linbase_golang_version != '' # noqa 602
  become: yes
  tags: linbase_golang


- name: tune kernel parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/77-system.conf
  with_dict: "{{ linbase_sysctl }}"
  loop_control:
    label: "{{ item.key | regex_replace('^net\\.') }}"
  when: allow_sysctl |bool
  tags: linbase_sysctl


- name: configure firewall
  import_tasks: firewall.yml
  when: lin_use_firewall |bool
  tags: linbase_firewall


- name: adjust global ssh settings
  import_tasks: ssh.yml
  when: lin_use_ssh |bool
  tags: linbase_ssh


- name: disable some motd banners
  import_tasks: motd.yml
  tags: linbase_motd
...
