---
- name: create swap file
  command: >
    dd if=/dev/zero "of={{ linbase_swap_file }}"
       bs=1M "count={{ linbase_swap_mb }}"
  args:
    creates: "{{ linbase_swap_file }}"
  register: swap_status_result

- name: set swap file permissions
  file:
    path: "{{ linbase_swap_file }}"
    mode: 0600

- name: format swap file
  command: mkswap "{{ linbase_swap_file }}"
  when: swap_status_result is changed

- name: add swap to fstab
  lineinfile:
    path: /etc/fstab
    line: "{{ linbase_swap_file }} none swap sw 0 0"
    regexp: "{{ linbase_swap_file }}"

- name: activate swap
  command: swapon -a
  when: swap_status_result is changed
...
