---
- name: create swap file
  block:
    - name: create swap file using fallocate (will rescue if it fails)
      command: fallocate -l "{{ lin_core_swap_mb }}M" "{{ lin_core_swap_file }}"
      args:
        creates: "{{ lin_core_swap_file }}"
      register: swap_status_result
  rescue:
    - name: create swap file using dd
      command: dd bs=1M "count={{ lin_core_swap_mb }}" if=/dev/zero "of={{ lin_core_swap_file }}"
      register: swap_status_result

- name: set swap file permissions
  file:
    path: "{{ lin_core_swap_file }}"
    mode: 0600

- name: format swap file
  command: mkswap "{{ lin_core_swap_file }}"
  when: swap_status_result is changed

- name: add swap file to fstab
  lineinfile:
    path: /etc/fstab
    line: "{{ lin_core_swap_file }} none swap sw 0 0"
    regexp: "{{ lin_core_swap_file }}"

- name: activate swap file
  command: swapon -a
  when: swap_status_result is changed
...
