---
- name: disable ubuntu motd banners by disabling execution (ok to fail)
  file:
    path: /etc/update-motd.d/{{ item }}
    mode: 0644
  loop:
    - 10-help-text
    - 50-landscape-sysinfo
    - 50-motd-news
    - 60-unminimize
    - 80-esm
    - 80-livepatch
    - 90-updates-available
    - 91-release-upgrade
    - 95-hwe-eol
  loop_control:
    label: "{{ item }}"
  failed_when: false
  no_log: "{{ hide_secrets |bool }}"

- name: disable ubuntu motd banners by renaming (ok to fail)
  command: mv /etc/update-motd.d/{{ item }} /etc/update-motd.d/{{ item }}.off
  args:
    removes: /etc/update-motd.d/{{ item }}
  loop: []
  loop_control:
    label: "{{ item }}"
  failed_when: false
  no_log: "{{ hide_secrets |bool }}"

- name: disable cron job motd-news
  systemd:
    name: motd-news.timer
    state: stopped
    enabled: false
  failed_when: false
  no_log: true
...
