---
- name: prepare systemd drop-in directory for {{ item.0 }} timer
  ansible.builtin.file:
    path: /etc/systemd/system/cron-{{ item.0 }}.timer.d
    state: directory
    mode: 0755

- name: adjust systemd calendar for {{ item.0 }} timer
  ansible.builtin.copy:
    dest: /etc/systemd/system/cron-{{ item.0 }}.timer.d/calendar.conf
    content: |
      [Timer]
      OnCalendar=
      OnCalendar={{ item.1 }}
    force: true
    mode: 0644
  notify: reload systemd daemon
...
