---
- block:
    - name: install core packages (ok to fail once, log hidden)
      ansible.builtin.apt:
        name: "{{ lin_core_packages_core }}"
      ## reduce verbose failure message
      no_log: "{{ hide_secrets |bool }}"
  rescue:
    - name: update apt cache and install core packages
      ansible.builtin.apt:
        name: "{{ lin_core_packages_core }}"
        update_cache: true
      ## reduce log thrashing in docker molecule tests
      no_log: "{{ is_molecule_test and is_docker_target }}"

- name: install system logger
  ansible.builtin.apt:
    name:
      - rsyslog
      - logrotate
    state: present
  when: lin_use_rsyslog |bool
  ## reduce log thrashing in docker molecule tests
  no_log: "{{ is_molecule_test and is_docker_target }}"

- block:
    - name: install core development packages (ok to fail once, log hidden)
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      no_log: "{{ hide_secrets |bool }}"
  rescue:
    - name: update apt lists and install core development packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
  vars:
    packages: "{{ lin_core_packages_devel |select |list }}"

## it may be a good idea to restart mitogen runner
## after installing python apt bindings
# - ansible.builtin.meta: reset_connection
...
