---
- name: adjust system settings
  ansible.builtin.import_tasks: settings.yml
  tags: lin_core_settings

- name: adjust apt settings
  ansible.builtin.import_tasks: apt.yml
  tags: lin_core_apt

- name: install core packages
  ansible.builtin.import_tasks: packages.yml
  tags: lin_core_packages


- name: synchronize system time
  # this task requires time packages (installed above)
  ansible.builtin.import_tasks: timesync.yml
  when: lin_core_time_sync |bool
  tags: lin_core_timesync

- name: adjust cron timers
  ansible.builtin.include_tasks: cron-adjust.yml
  args:
    apply:
      tags: lin_core_cron
      become: true
  loop: "{{ lin_cron_timers |dictsort }}"
  loop_control:
    label: "{{ item.0 }}"
  when: lin_cron_adjust |bool
  tags: lin_core_cron

- name: setup cron tasks
  ansible.builtin.import_tasks: cron-tasks.yml
  tags: lin_core_cron


- name: adjust kernel parameters
  ansible.builtin.import_tasks: kernel.yml
  when: allow_sysctl |bool
  tags:
    - lin_core_sysctl
    - lin_core_kernel

- name: setup swap space
  ansible.builtin.import_tasks: swap.yml
  when:
    - lin_core_swap_enable |bool
    - lin_core_swap_mb |int > 0
  tags: lin_core_swap


- name: derive ssh port
  ansible.builtin.set_fact:
    real_ssh_port: "{{ real_ssh_port
                     | default(ansible_port)
                     | default(ansible_ssh_port)
                     | default(22) }}"
  tags:
    - lin_ferm_rules
    - lin_ferm_all
    - lin_core_ssh
    - lin_core_firewall

- name: configure port for ssh service
  ansible.builtin.import_tasks: ssh.yml
  when: lin_use_ssh |bool
  tags: lin_core_ssh

- name: setup firewall
  ansible.builtin.import_tasks: firewall.yml
  tags: lin_core_firewall


- name: disable telemetry on ubuntu bionic+
  ansible.builtin.import_tasks: telemetry.yml
  when: ansible_lsb.release is version('18.04','>=')
  tags: lin_core_telemetry

- name: disable unattended upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: absent
  tags: lin_core_apt

- name: install helper scripts
  ansible.builtin.copy:
    src: "utils/{{ item }}.sh"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - clear-rootfs
    - clear-swap
  tags: lin_core_utils
...
