---
- name: configure port for ssh service
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#*\s*Port\b'
    line: 'Port {{ real_ssh_port }}'
    backrefs: false
    insertbefore: "^Match|^Subsystem|^# *BEGIN"
    firstmatch: true
  notify: restart ssh service

- name: enable ssh service
  ansible.builtin.systemd:
    name: ssh
    state: started
    enabled: true
...
