---
# reboot and wait to come back

- name: warn user and wait for confirmation
  include_tasks: pause.yml
  when: "linref_reboot_pause != 'nowait'"

- name: reboot machine
  shell: sleep 1 && shutdown -r now
  # async+poll prevents conection errors
  # see: https://superuser.com/a/1106350
  async: 1
  poll: 0
  ignore_errors: yes
  changed_when: false

- debug:
    msg: "{{ inventory_hostname }} is rebooting.."

- wait_for_connection:
    delay: "{{ linref_reboot_probe_delay }}"
    timeout: "{{ linref_reboot_probe_timeout }}"
  register: wait_result

- debug:
    msg: "{{ inventory_hostname }} is back online!"
  when: wait_result is successful
...
