---
- name: synchronize system time
  import_tasks: timesync.yml
  when: linref_time_sync | bool == true
  tags: linref_timesync

- name: perform upgrade
  import_tasks: upgrade.yml
  tags: linref_upgrade

- name: check for reboot marker
  stat:
    path: "{{ linref_reboot_marker }}"
    get_checksum: no
    get_mime: no
  register: reboot_marker
  tags: linref_reboot

- name: reboot and wait to come back
  import_tasks: reboot.yml
  when: "reboot_marker.stat.exists == true
         and linref_reboot_allow | bool == true
         or linref_reboot_always | bool == true"
  tags: linref_reboot

- debug:
    msg: "please reboot {{ inventory_hostname }} manually"
  when: "reboot_marker.stat.exists == true
         and linref_reboot_allow | bool == false"
  tags:
    - linref_upgrade
    - linref_reboot
...
