---
- name: synchronize system time
  import_tasks: timesync.yml
  when: linref_time_sync |bool
  tags: linref_timesync

- name: perform upgrade
  import_tasks: upgrade.yml
  tags: linref_upgrade

- name: check for reboot marker
  stat:
    path: "{{ linref_reboot_marker }}"
    get_checksum: no
    get_mime: no
  register: reboot_marker
  tags: linref_reboot

- name: reboot after kernel upgrade
  reboot:
    pre_reboot_delay: 20
  when: reboot_marker.stat.exists
        and allow_reboot |bool
        or linref_reboot_always |bool
  tags: linref_reboot

- name: ask user to reboot
  debug:
    msg: "please reboot {{ inventory_hostname }} manually"
  when: reboot_marker.stat.exists
        and not allow_reboot |bool
  tags: linref_reboot
...
