---
# synchronize system time

- block:
    - name: install time packages
      apt:
        name: [ ntp, ntpdate ]
  rescue:
    - name: install time packages and update apt
      apt:
        name: [ ntp, ntpdate ]
        update-cache: yes

- name: pause ntp daemon
  systemd:
    name: ntp
    state: stopped
  changed_when: "linref_time_visible_changes | bool"

- name: step-sync local time
  command: ntpdate "{{ linref_time_server }}"
  changed_when: "linref_time_visible_changes | bool"

- name: resume ntp daemon
  systemd:
    name: ntp
    state: started
    enabled: yes
  changed_when: "linref_time_visible_changes | bool"
...
