---
- name: setup yggdrasil systemd service
  template:
    src: yggdrasil.service.j2
    dest: /etc/systemd/system/yggdrasil.service
    mode: 0644
  register: _ygg_serv_result
  notify: restart yggdrasil service
  tags: lin_ygg_service

- name: remove yggdrasil auto-config service
  file:
    path: /etc/systemd/system/yggdrasil-default-config.service
    state: absent
  notify: reload systemd daemon
  tags: lin_ygg_service

- name: enable yggdrasil service
  systemd:
    name: yggdrasil
    state: started
    enabled: true
    daemon_reload: "{{ repo_changed or dpkg_changed or serv_changed }}"
  vars:
    repo_changed: "{{ _ygg_repo_result |d({}) is changed }}"
    dpkg_changed: "{{ _ygg_dpkg_result |d({}) is changed }}"
    serv_changed: "{{ _ygg_serv_result |d({}) is changed }}"
  tags: lin_ygg_service
...
