---
- name: generate restic weekly prune script
  template:
    src: prune.sh.j2
    dest: /etc/restic/prune.sh
    owner: restic
    group: rclone
    mode: 0750
  vars:
    verb_opts: "{{ ('--verbose=%s ' % lin_restic_cron_verbose)
                   if (lin_restic_cron_verbose |int > 0) else '' }}"
    forget_opts: >-
      --keep-last={{ lin_restic_forget_keep_last }}
      --keep-daily={{ lin_restic_forget_keep_daily }}
      --keep-weekly={{ lin_restic_forget_keep_weekly }}
      --keep-monthly={{ lin_restic_forget_keep_monthly }}
      --keep-yearly={{ lin_restic_forget_keep_yearly }}
    hide_stream_reset_clause: "{{ lin_restic_hide_stream_reset |bool |ternary(_hide_stream_reset_clause, '') }}"
    _hide_stream_reset_clause: " 2>&1 | grep -v 'finish writing GET request'"
  register: restic_prune_script_result
  notify: reload systemd daemon

- name: setup restic weekly prune service
  template:
    src: prune.service.j2
    dest: /etc/systemd/system/restic-prune.service
    mode: 0644
  register: restic_prune_service_result
  notify: reload systemd daemon

- name: configure restic weekly prune timer
  template:
    src: prune.timer.j2
    dest: /etc/systemd/system/restic-prune.timer
    mode: 0644
  register: restic_prune_timer_result
  notify: reload systemd daemon
  vars:
    day: "{{ lin_restic_cron_day_prune |d('Mon', true) }}"
    time: "{{ lin_restic_cron_time_prune |d('7:30', true) }}"

- name: (de)activate restic weekly prune job
  systemd:
    name: restic-prune.timer
    state: "{{ active |ternary('started', 'stopped') }}"
    enabled: "{{ active }}"
    daemon_reload: "{{ script_changed or service_changed or timer_changed }}"
  vars:
    day: "{{ lin_restic_cron_day_prune |d('',true) }}"
    time: "{{ lin_restic_cron_time_prune |d('',true) }}"
    active: "{{ true if day and time else false }}"

    script_changed: "{{ restic_prune_script_result is changed }}"
    service_changed: "{{ restic_prune_service_result is changed }}"
    timer_changed: "{{ restic_prune_timer_result is changed }}"
...
