---
- name: install restic binary
  import_tasks: install.yml
  tags: lin_restic_install

- name: create restic config directory
  file:
    path: /etc/restic
    state: directory
    owner: root
    group: rclone
    mode: 0750

- name: create dedicated restic user
  import_tasks: user.yml
  tags: lin_restic_user

- name: setup rclone remote for restic
  include_role:
    name: ivansible.linux.rclone
    tasks_from: _mount.yml
    apply:
      become: true
      tags: lin_restic_rclone
  vars:
    item:
      name: "{{ lin_restic_rclone_remote }}"
      config: "{{ lin_restic_rclone_config }}"
      path: ''
      token: "{{ lin_restic_rclone_token }}"
      reuse_token: "{{ lin_restic_rclone_reuse_token }}"
      fstab_default: false
  when: lin_restic_rclone_config |d('')
  tags: lin_restic_rclone

- name: verify that restic repository is already created
  command: restic cat config
  register: restic_repo_check
  changed_when: not restic_repo_check.stdout |d('')
  failed_when: false
  environment:
    RESTIC_REPOSITORY: "{{ lin_restic_repository }}"
    RESTIC_PASSWORD: "{{ lin_restic_password }}"
    RCLONE_CONFIG: "{{ lin_rclone_config }}"
  tags: lin_restic_repo

- name: setup new restic repository
  ## hide real hostname from repo keys
  shell: |
    name=$(hostname)
    hostname host
    restic init && ok=1 || ok=0
    hostname $name
    test $ok = 1
  environment:
    RESTIC_REPOSITORY: "{{ lin_restic_repository }}"
    RESTIC_PASSWORD: "{{ lin_restic_password }}"
    RCLONE_CONFIG: "{{ lin_rclone_config }}"
  when: restic_repo_check is changed
  tags: lin_restic_repo

- name: setup restic mount
  import_tasks: mount.yml
  when: lin_restic_mount_dir |d('')
  tags: lin_restic_mount

- name: activate restic backup job
  import_tasks: backup.yml
  tags: lin_restic_cron

- name: activate restic prune job
  import_tasks: prune.yml
  tags: lin_restic_cron
...
