---
- name: become root and configure ssh daemon
  ansible.builtin.import_tasks: root.yml
  become: true
  when: lin_use_ssh |bool
  tags: lin_ssh_all

- name: apply new ssh settings
  ansible.builtin.meta: flush_handlers
  tags: lin_ssh_all
...
