---
## handlers for ivansible.lin_ferm

- name: reload ferm service
  # noqa command-instead-of-module
  ansible.builtin.command: systemctl reload-or-restart ferm.service
  become: true
  register: _ferm_service_reload
  until: _ferm_service_reload is successful
...
