---
# handlers for ivansible.lin_net

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: true
  become: true

- name: restart ntp daemon
  systemd:
    name: ntp
    state: restarted
  become: true
  ignore_errors: true
...
