---
- name: add keepalived ppa
  apt_repository:
    repo: ppa:hnakamur/keepalived
    filename: keepalived
    mode: 0644
  when: kad_install_from_ppa |bool

- name: install keepalived packages
  block:
    - name: install keepalived packages (will rescue if fails)
      apt:
        name: "{{ packages }}"
      register: _keepalived_apt_result
  rescue:
    - name: install keepalived packages (update cache)
      apt:
        name: "{{ packages }}"
        update_cache: true
      register: _keepalived_apt_result
  vars:
    packages: keepalived,fping

- name: directory for keepalived config and scripts
  file:
    path: /etc/keepalived
    state: directory
    mode: 0755

- name: initialize keepalived config
  template:
    src: defaults.conf
    dest: /etc/keepalived/keepalived.conf
    force: "{{ _keepalived_apt_result is changed or kad_reset |bool }}"
    mode: 0644
  notify: restart keepalived service

- name: add user config to keepalived
  blockinfile:
    path: /etc/keepalived/keepalived.conf
    block: "{{ kad_user_config }}"
    marker: '# {mark} USER CONFIG'
  notify: restart keepalived service

- name: add dynamic routes to keepalived
  blockinfile:
    path: /etc/keepalived/keepalived.conf
    block: "{{ lookup('template', 'route.conf') if enabled else '# disabled' }}"
    marker: "# {mark} ROUTE {{ name }}"
  notify: restart keepalived service
  when: kad_router_enable |bool
  loop: "{{ kad_routes }}"
  loop_control:
    label: "{{ name }}"
  vars:
    name: "{{ item.name }}"
    device: "{{ kad_router_vip_device }}"
    metric: "{{ kad_router_vip_metric }}"

    beacons: "{{ [item.beacons] |flatten |join(',') }}"
    _targets: "{{ [item.targets] |flatten }}"
    targets4: "{{ _targets |ternary(_targets |ipv4, []) |join(',') |d('-',true) }}"
    targets6: "{{ _targets |ternary(_targets |ipv6, []) |join(',') |d('-',true) }}"

    vip4: "{{ item.vip_addr4 |d('') }}"
    vip6: "{{ item.vip_addr6 |d('') }}"
    rid4: "{{ item.router_id4 |d(0) |int }}"
    rid6: "{{ item.router_id6 |d(0) |int }}"

    use4: "{{ vip4 and rid4 and targets4 != '-' and kad_router_use_ip4 |bool }}"
    use6: "{{ vip6 and rid6 and targets6 != '-' and kad_router_use_ip6 |bool }}"
    enabled: "{{ beacons and (use4 or use6) }}"

    random_seed: "{{ '%s@%s' |format(name, inventory_hostname) }}"
    random_ping_max: "{{ kad_ping_randomize |int + 1 }}"
    random_ping: "{{ random_ping_max |int |random(0, seed=random_seed) }}"

- name: make helper scripts for dynamic routes
  copy:
    src: "{{ item }}"
    dest: "/etc/keepalived/{{ item }}"
    force: true
    mode: 0755
  loop:
    - route-ping.sh
    - route-ctl.sh
  notify: restart keepalived service

- name: activate keepalived service
  systemd:
    name: keepalived
    state: started
    enabled: true
    daemon_reload: true

- name: allow vrrp traffic in ferm
  ferm_rule:
    name: vrrp
    prio: 34
    rule: |
      # keepalived
      domain $ip_all table filter {
        chain $INPUT  proto vrrp  jump FERM-HOSTS-EXTERNAL;
        chain FERM-HOSTS-INTERNAL  proto vrrp  ACCEPT;
      }
  tags: skip_ansible_lint
  when: lin_firewall == 'ferm'

- name: allow gratuitous keepalived routes
  sysctl:
    name: "net.ipv4.conf.{{ item }}.rp_filter"
    value: '0'
    sysctl_file: /etc/sysctl.d/77-liveroutes.conf
  loop: "{{ [kad_router_vip_device] }}"
  when: allow_sysctl |bool

- name: fix sysctl file mode
  file:
    path: /etc/sysctl.d/77-liveroutes.conf
    mode: 0644
  when: allow_sysctl |bool

- name: configure keepalived logging
  import_tasks: syslog.yml
  when: kad_use_rsyslog |bool
  tags: lin_kad_syslog
...
