---
- name: add keepalived ppa
  apt_repository:
    repo: ppa:hnakamur/keepalived
    filename: keepalived
    mode: 0644
  when: kad_install_from_ppa |bool

- name: install keepalived packages
  apt:
    name:
      - keepalived
      - fping
  register: _keepalived_apt_result

- name: directory for keepalived config and scripts
  file:
    path: /etc/keepalived
    state: directory
    mode: 0755

- name: initialize keepalived config
  template:
    src: defaults.conf
    dest: /etc/keepalived/keepalived.conf
    force: "{{ _keepalived_apt_result is changed or kad_reset |bool }}"
    mode: 0644
  notify: restart keepalived service

- name: add user config to keepalived
  blockinfile:
    path: /etc/keepalived/keepalived.conf
    block: "{{ kad_user_config }}"
    marker: '# {mark} USER CONFIG'
  notify: restart keepalived service

- name: add dynamic routes to keepalived
  blockinfile:
    path: /etc/keepalived/keepalived.conf
    block: "{{ lookup('template', 'route.conf') if enabled |bool else '# disabled' }}"
    marker: "# {mark} ROUTE {{ name }}"
  notify: restart keepalived service
  when: kad_router_enable |bool
  loop: "{{ kad_routes }}"
  loop_control:
    label: "{{ name }}"
  vars:
    name: "{{ item.name }}"
    target: "{{ item.target }}"
    vip: "{{ item.vip_addr }}"
    gates: "{{ item.gateways }}"
    dev: "{{ kad_router_vip_device }}"
    prio: "{{ kad_router_vip_prio }}"
    router_id: "{{ item.router_id }}"

    ipv6: "{{ ':' in target }}"
    proto: "{{ ipv6 |ternary('-6','-4') }}"
    unicast_ip: "{{ ipv6 |ternary(kad_unicast_ip6, kad_unicast_ip4) }}"
    unicast_peers: "{{ ipv6 |ternary(kad_unicast_peers6, kad_unicast_peers4) }}"
    enabled: "{{ ipv6 |ternary(kad_router_use_ip6, kad_router_use_ip4) |bool }}"

    random_seed: "{{ '%s@%s' |format(name, inventory_hostname) }}"
    random_ping_max: "{{ kad_ping_randomize |int + 1 }}"
    random_ping: "{{ random_ping_max |int |random(0, seed=random_seed) }}"

- name: make helper scripts for dynamuc routes
  template:
    src: "{{ item }}"
    dest: "/etc/keepalived/{{ item }}"
    mode: 0755
  loop:
    - route-ping.sh
    - route-ctl.sh

- name: activate keepalived service
  systemd:
    name: keepalived
    state: started
    enabled: true
    daemon_reload: true

- name: allow vrrp traffic in ferm
  ferm_rule:
    name: vrrp
    prio: 34
    rule: "{{ lookup('template', 'vrrp.ferm') }}"
  tags: skip_ansible_lint

- name: allow gratuitous keepalived routes
  sysctl:
    name: "net.ipv4.conf.{{ item }}.rp_filter"
    value: '0'
    sysctl_file: /etc/sysctl.d/77-liveroutes.conf
  loop: "{{ [kad_router_vip_device] }}"

- name: fix mode of the sysctl file
  file:
    path: /etc/sysctl.d/77-liveroutes.conf
    mode: 0644
...
