---
lin_ssh_pam: true
lin_motd_banner: true

lin_ssh_known_hosts:
  - github.com
  - gitlab.com

lin_ssh_settings:
  ## fix ssh port
  Port: "{{ real_ssh_port |default(ansible_port) |default(22) }}"
  ## disable insecure login methods
  Protocol: '2'
  IgnoreRhosts: 'yes'
  HostbasedAuthentication: 'no'
  ChallengeResponseAuthentication: 'no'
  ## disable password authentication
  PasswordAuthentication: 'no'
  PermitEmptyPasswords: 'no'
  PermitRootLogin: 'no'
  UsePAM: "{{ lin_ssh_pam |bool |ternary('yes','no') }}"
  ## don't delay logins by banners
  ## https://linuxquestions.org/questions/linux-security-4/how-to-disable-ssh-version-banner-909540
  DebianBanner: "{{ lin_motd_banner |bool |ternary('yes','no') }}"
  PrintMotd: "{{ lin_motd_banner |bool |ternary('yes','no') }}"
  PrintLastLog: "{{ lin_motd_banner |bool |ternary('yes','no') }}"
  ## don't delay logins by incoming host checks
  UseDNS: 'no'
  ## rekey limits
  ## https://man.openbsd.org/ssh_config#RekeyLimit
  ## http://manpages.ubuntu.com/manpages/bionic/man5/sshd_config.5.html#time%20formats
  RekeyLimit: '1G 2h'
  ## keepalive every minute
  ClientAliveInterval: '60'
  ## harden security as recommended by Lynis
  ClientAliveCountMax: '2'
  TCPKeepAlive: 'no'
  Compression: 'no'
  MaxAuthTries: '2'
  MaxSessions: '2'
  AllowTcpForwarding: 'no'
  AllowAgentForwarding: 'no'
  X11Forwarding: 'no'

lin_ssh_superuser_settings:
  MaxSessions: 6
  AllowTcpForwarding: 'yes'
  AllowAgentForwarding: 'yes'
  X11Forwarding: 'yes'
  ## this one isn't supported n match blocks on xenial
  ClientAliveCountMax: "{{ lin_ssh_idle_timeout_minutes if ansible_lsb.release is version('16.04','>') else '' }}"

lin_ssh_superusers: ["{{ ansible_user_id }}"]

lin_ssh_root_login_from: ~

lin_ssh_idle_timeout_minutes: 10

# up to 10 connections per minute per ip
lin_ssh_conn_limit: 10/min
lin_ssh_conn_burst: 5
...
