---
# defaults for ivansible.lin_ssh

lin_ssh_known_hosts:
  - github.com
  - gitlab.com

lin_ssh_settings:
  ## fix ssh port
  Port: "{{ real_ssh_port |default(ansible_port) |default(22) }}"
  ## disable insecure login methods
  Protocol: '2'
  IgnoreRhosts: 'yes'
  HostbasedAuthentication: 'no'
  ChallengeResponseAuthentication: 'no'
  ## disable password authentication
  PasswordAuthentication: 'no'
  PermitEmptyPasswords: 'no'
  PermitRootLogin: 'no'
  UsePAM: 'no'
  ## don't delay logins by banners
  ## https://linuxquestions.org/questions/linux-security-4/how-to-disable-ssh-version-banner-909540
  DebianBanner: 'no'
  PrintMotd: 'no'
  PrintLastLog: 'no'
  ## don't delay logins by incoming host checks
  UseDNS: 'no'
  ## keepalive every minute
  TCPKeepAlive: 'yes'
  ClientAliveInterval: '60'
  ClientAliveCountMax: "{{ lin_ssh_idle_timeout_minutes }}"
  ## rekey limits
  ## https://man.openbsd.org/ssh_config#RekeyLimit
  ## http://manpages.ubuntu.com/manpages/bionic/man5/sshd_config.5.html#time%20formats
  RekeyLimit: '1G 2h'


lin_ssh_idle_timeout_minutes: 10

# up to 10 connections per second
lin_ssh_conn_limit: 1/sec
lin_ssh_conn_burst: 9
...
