---
# defaults for ivansible.lin_ssh

lin_ssh_known_hosts:
  - github.com
  - gitlab.com

lin_ssh_settings:
  ## fix ssh port
  Port: "{{ real_ssh_port |default(ansible_port) |default(22) }}"
  ## disable insecure login methods
  Protocol: '2'
  IgnoreRhosts: 'yes'
  HostbasedAuthentication: 'no'
  ChallengeResponseAuthentication: 'no'
  ## disable password authentication
  PasswordAuthentication: 'no'
  PermitEmptyPasswords: 'no'
  PermitRootLogin: 'no'
  UsePAM: 'no'
  ## keepalive every minute
  TCPKeepAlive: 'yes'
  ClientAliveInterval: '60'
  ClientAliveCountMax: "{{ lin_ssh_idle_timeout_minutes }}"
  ## don't delay logins for banners
  ## https://linuxquestions.org/questions/linux-security-4/how-to-disable-ssh-version-banner-909540
  DebianBanner: 'no'
  PrintMotd: 'no'
  PrintLastLog: 'no'
  ## don't delay logins for incoming host checks
  UseDNS: 'no'

lin_ssh_idle_timeout_minutes: 10
...
