---
# True setting will point /etc/apt/sources.list to yandex mirrors
# if host belongs to the "vagrant" group. To keep your apt sources
# intact, set this to false.
linref_apt_sources: true

linref_allow_universe: true

linref_allow_src: true

linref_allow_backports: true

linref_time_server: pool.ntp.org

linref_time_visible_changes: false

linref_reboot_marker: /var/run/reboot-required

linref_reboot_allow: true

# let 10 seconds to commence reboot
linref_reboot_delay: 10

# 5 minute timeout
linref_reboot_timeout: 300
...
