---
# synchronize system time

- block:
    - name: install time packages
      apt:
        name:
          - ntp
          - ntpdate
          # timedatectl requires dbus, see https://askubuntu.com/a/1015391
          - dbus
  rescue:
    - name: install time packages and update apt
      apt:
        name:
          - ntp
          - ntpdate
          - dbus
        update-cache: true

- name: enable ntp sync
  command: timedatectl set-ntp true
  changed_when: not linref_time_hide_changes |bool

- name: activate ntp daemon
  systemd:
    name: ntp
    state: started
    enabled: true
  changed_when: not linref_time_hide_changes |bool

- name: step-sync local time
  # "-u" = use unprivileged port for outgoing packets,
  # helps when ntp service is running (or against firewalls),
  # so we don't have to stop/start ntp service
  command: ntpdate -u "{{ linref_time_server }}"
  changed_when: not linref_time_hide_changes |bool
...
