---
## defaults for ivansible.linux.net

## static address on loopback
lin_net_lo4: ~
lin_net_lo6: ~

lin_net_interfaces_files: [interfaces]

## prevent ntp daemon from picking docker veth interfaces
## by default ntp daemon listens on all interfaces
lin_net_ntp_interfaces: ~  # ['eth*', 'ens*']

## DNS resolver
lin_net_dns_servers: [1.1.1.1, 8.8.8.8]
lin_net_enable_resolved: "{{ ansible_lsb.release is version('16.04','>') }}"

lin_net_resolved_settings:
  DNS: "{{ lin_net_dns_servers |join(' ') }}"
  ## Setting global route-only domain avoids the
  ## resolving completely taken over by a link.
  Domains: '~.'
  Cache: 'yes'
  DNSStubListener: 'yes'
  DNSSEC: 'no'
  MulticastDNS: 'no'
  LLMNR: 'no'

## miscellaneous
lin_net_port_trace6: 33434
...
