---
## vxlan settings

lin_vxlan_enable: false
lin_vxlan_device: vxlan0
lin_vxlan_id: 0
lin_vxlan_ip4: ~
lin_vxlan_ip6: ~
lin_vxlan_prefix4: 24
lin_vxlan_prefix6: 64

lin_vxlan_port: 4789
lin_vxlan_base_ip: "{{ lin_vxlan_enable |bool |ternary(ansible_default_ipv4.address |d(ansible_default_ipv6.address), none) }}"
lin_vxlan_base_device: "{{ ansible_default_ipv4.interface |d(ansible_default_ipv6.interface) }}"

lin_vxlan_group: ~
lin_vxlan_peer_ips: "{{ groups[lin_vxlan_group] |d([]) |map('extract', hostvars, 'lin_vxlan_base_ip') |select |sort }}"
...
