---
branches:
  only:
    - master
    - /^v/
language: python
python: 3.6
os: linux

env:
  global:
    - ROLE_NAME=ivansible.lin_system

before_install:
  - ln -s $TRAVIS_BUILD_DIR $(dirname $TRAVIS_BUILD_DIR)/$ROLE_NAME

install:
  - pip3 install -U pip setuptools wheel
  # molecule pulls: ansible-lint yamllint flake8 pytest testinfra
  - pip3 install molecule docker

matrix:
  include:
    - name: test on xenial
      dist: xenial
      env:
        - IVATEST_FIREWALL=true
      script:
        - molecule test -s localhost

    - name: test on bionic
      dist: bionic
      env:
        - IVATEST_FIREWALL=true
      script:
        - molecule test -s localhost

    - name: tests in docker
      dist: bionic
      services: docker
      env:
        - IVATEST_FIREWALL=false
      script:
        - molecule lint
        - molecule destroy
        - molecule dependency
        - molecule syntax
        - molecule create
        - molecule converge
        - travis_wait 30 molecule idempotence
        - molecule verify
        - molecule destroy
...
