---
- name: setup keepalived
  ansible.builtin.import_tasks: root.yml
  become: true
  when: kad_enable |bool
  tags: lin_kad_all

- name: run postponed tasks
  ansible.builtin.meta: flush_handlers
  tags: lin_kad_all
...
