---
- name: add keepalived ppa
  apt_repository:
    repo: ppa:hnakamur/keepalived
    filename: keepalived
    mode: 0644
  when: kad_install_from_ppa |bool
  tags: lin_kad_install

- name: install keepalived packages
  block:
    - name: install keepalived packages (will rescue if fails)
      apt:
        name: "{{ packages }}"
      register: _keepalived_apt_result
  rescue:
    - name: install keepalived packages (update cache)
      apt:
        name: "{{ packages }}"
        update_cache: true
      register: _keepalived_apt_result
  vars:
    packages: keepalived,fping
  tags: lin_kad_install

- name: directory for keepalived config and scripts
  file:
    path: /etc/keepalived
    state: directory
    mode: 0755
  tags: lin_kad_install

- name: initialize keepalived config
  template:
    src: defaults.conf
    dest: /etc/keepalived/keepalived.conf
    force: "{{ _keepalived_apt_result is changed or kad_reset |bool }}"
    mode: 0644
  notify: restart keepalived service
  tags: lin_kad_config

- name: add user config to keepalived
  blockinfile:
    path: /etc/keepalived/keepalived.conf
    block: "{{ kad_user_config }}"
    marker: '# {mark} USER CONFIG'
  notify: restart keepalived service
  tags: lin_kad_config

- name: setup dynamic routes
  import_tasks: routes.yml
  when: kad_router_enable |bool
  tags: lin_kad_routes

- name: activate keepalived service
  systemd:
    name: keepalived
    state: started
    enabled: true
    daemon_reload: "{{ _kad_router_systemd_dropin |d({}) is changed }}"
  tags: lin_kad_service

- name: allow vrrp traffic in ferm
  ferm_rule:
    name: vrrp
    prio: 34
    rule: |
      # keepalived
      domain $ip_all table filter {
        chain $INPUT  proto vrrp  jump FERM-HOSTS-EXTERNAL;
        chain FERM-HOSTS-INTERNAL  proto vrrp  ACCEPT;
      }
  when: lin_firewall == 'ferm'
  tags: [skip_ansible_lint, lin_kad_firewall]

- name: configure keepalived logging
  import_tasks: syslog.yml
  when: kad_use_rsyslog |bool
  tags: lin_kad_syslog
...
