---
- name: configure dns servers in systemd-resolved
  lineinfile:
    path: /etc/systemd/resolved.conf
    line: "{{ item.param }}={{ item.value }}"
    regexp: "^\\s*#*\\s*{{ item.param }}\\s*="
  loop:
    - {param: DNS, value: "{{ lin_net_dns_servers |join(' ') }}"}
    - {param: Cache, value: 'yes'}
    - {param: DNSStubListener, value: 'yes'}
  loop_control:
    label: "{{ item.param }}"
  notify: restart systemd-resolved
  when: lin_net_enable_systemd_resolved |bool
...
