---
- name: configure systemd-resolved
  lineinfile:
    path: /etc/systemd/resolved.conf
    line: "{{ item.0 }}={{ item.1 }}"
    regexp: "^\\s*#*\\s*{{ item.0 }}\\s*="
    ## Note: we control the *last* DNS= line
    ##       letting user *prepend* custom DNS= servers!
    firstmatch: false
  loop: "{{ lin_net_resolved_settings |dictsort }}"
  loop_control:
    label: "{{ item.0 }}"
  notify: restart systemd-resolved
  when: lin_net_enable_resolved |bool
...
