---
- name: prepare ifupdown interfaces file
  import_tasks: ifupdown.yml
  tags: lin_net_ifupdown

- name: setup loopback address
  import_tasks: loopback.yml
  when: lin_net_lo4 |default('')
        or lin_net_lo6 |default('')
  tags: lin_net_loopback

- name: setup dns
  import_tasks: dns.yml
  tags: lin_net_dns

- name: setup ipv6 from hurricane electric
  include_tasks: he6.yml
  when: lin_he6_enable |bool
  args:
    apply:
      become: true
      tags:
        - lin_net_he6
        - lin_net_all
  tags: lin_net_he6

- name: setup vxlan
  include_tasks: vxlan.yml
  when: lin_vxlan_enable |bool
  args:
    apply:
      become: true
      tags:
        - lin_net_vxlan
        - lin_net_all
  tags: lin_net_vxlan

- name: prevent ntp from listening on virtual interfaces like veth
  lineinfile:
    path: /etc/ntp.conf
    line: "interface listen {{ item }}"
  loop: "{{ lin_net_ntp_interfaces |d([],1) }}"
  tags: lin_net_ntp
  notify: restart ntp daemon
...
