---
## defaults for ivansible.lin_wireguard
##
## commands to generate keys:
## wg genkey | tee key | wg pubkey; cat key
## wg genpsk
##

lin_wg_host: "{{ ansible_default_ipv4.address }}"
lin_wg_forward: true
lin_wg_public_interface: "{{ ansible_default_ipv4.interface |d(ansible_default_ipv6.interface) }}"

lin_wg_nets: []
# - name: net1         - name of subnet, informational (optional)
#   port: 0            - port to listen, 0 to not listen (optional)
#   addr: 10.1.1.1/24  - local peer address on subnet (REQUIRED)
#   key: ~             - private key (required)
#   pub: ~             - public key, informational (optional)
#   psk: ~             - pre-shared key (optional)
#   mtu: 0             - MTU for subnet (default: autodetect)
#   keepalive: 0       - keepalive interval in seconds (default: no keepalive)
#   metric: 0          - metric for peer routes (optional)
#   peers: []          - list of peers on the wireguard subnet
#     - name: peer1      - peer name, informational (REQUIRED)
#       active: true     - optional flag (default: true)
#       key: xxx         - private key, informational (optional)
#       pub: yyy         - public key (REQUIRED)
#       psk: zzz         - preshared key (optional)
#       ips: [ip/mask]   - allowed IPs, list of ip/mask pairs (optional)
#       host: ip         - IP address of endpoint (optional)
#       port: port       - port of endpoint, optional (default: subnet's port)
#       keepalive: 0     - keepalive interval in seconds (default: no keepalive)
#       redirect_gateway: true|false|ipv4|ipv6 - redirects outgoing traffic over vpn (default: false)
#       client_config: true|false     - produce example client config (default: false)
#       client_ips: [ip/mask]         - override client ip list in client config (optional)
#       server_ips: [ip/mask]         - override server ip list in client config (optional)

lin_wg_install_go: "{{ ansible_kernel is version('3.1', '<') }}"
lin_wg_go_binary: /usr/bin/wireguard-go
lin_wg_go_upgrade: false
...
