---
# defaults for ivansible.lin_net

## static address on loopback
lin_net_lo4: ~
lin_net_lo6: ~

lin_net_interfaces_files: [interfaces]

## prevent ntp daemon from picking docker veth interfaces
## by default ntp daemon listens on all interfaces
lin_net_ntp_interfaces: ~  # ['eth*', 'ens*']

## DNS resolver
lin_net_dns_servers: [1.1.1.1, 8.8.8.8]
lin_net_enable_resolved: "{{ ansible_lsb.release is version('16.04','>') }}"

lin_net_resolved_settings:
  DNS: "{{ lin_net_dns_servers |join(' ') }}"
  ## Setting global route-only domain avoids the
  ## resolving completely taken over by a link.
  Domains: '~.'
  Cache: 'yes'
  DNSStubListener: 'yes'
  DNSSEC: 'no'
  MulticastDNS: 'no'
  LLMNR: 'no'

## Hurricane Electric IPv6
lin_he6_enable: false
lin_he6_local: "{{ ansible_default_ipv4.address }}"
lin_he6_endpoint: 127.0.0.1
lin_he6_net64: 2001:470:aaa:bbb::/64
lin_he6_net48: 2001:470:ccc::/48

lin_he6_gateway6: "{{ lin_he6_net64 |ipmath(1) }}"
lin_he6_address6: "{{ lin_he6_net64 |ipmath(2) }}"
lin_he6_net32: 2001:470::/32

lin_he6_device: he0
lin_he6_metric: 3192

## loopback ip for testing
lin_he6_loopip: beef

## vxlan settings
lin_vxlan_enable: false
lin_vxlan_device: vxlan0
lin_vxlan_id: 0
lin_vxlan_ip4: ~
lin_vxlan_ip6: ~
lin_vxlan_prefix4: 24
lin_vxlan_prefix6: 64

lin_vxlan_port: 4789
lin_vxlan_base_ip: "{{ lin_vxlan_enable |bool |ternary(ansible_default_ipv4.address |d(ansible_default_ipv6.address), none) }}"
lin_vxlan_base_device: "{{ ansible_default_ipv4.interface |d(ansible_default_ipv6.interface) }}"

lin_vxlan_group: ~
lin_vxlan_peer_ips: "{{ groups[lin_vxlan_group] |d([]) |map('extract', hostvars, 'lin_vxlan_base_ip') |select |sort }}"

## miscellaneous
lin_net_port_trace6: 33434
...
