---
dependencies:
  - ivansible.lin_base  # for lin_use_rsyslog, lin_firewall, allow_sysctl

galaxy_info:
  role_name: lin_keepalived
  author: "Ivan Andreev"
  description: "deploy keepalived on linux"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - ansible

  github_branch: master
...
