---
dependencies: []

galaxy_info:

  author: "Ivan Andreev"
  description: "Perform basic configuration of a linux box"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - apt
    - ntp

  github_branch: master
...
