---
- name: add docker signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    filename: docker-ce

- block:
    - name: install docker and friends
      apt:
        name:
          - docker-ce
          - jq  # jq makes parsing docker output convenient
          - bash-completion
        state: present
  rescue:
    - name: install docker and friends, update apt cache
      apt:
        name:
          - docker-ce
          - jq  # jq makes parsing docker output convenient
          - bash-completion
        state: present
        update_cache: yes

- name: bash completion script for docker
  file:
    src: /usr/share/bash-completion/completions/docker
    dest: /etc/bash_completion.d/docker
    state: link

- name: enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes
...
