---
- name: add target user in the docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: yes

- name: install extra docker login dependencies on bionic
  # Docker login on Bionic defaults to use the secretservice executable
  # which seems to have some sort of X11 dependency for some reason.
  # This results in error "Cannot autolaunch D-Bus without X11 $DISPLAY"
  # If you install and configure `pass`, docker will use that instead,
  # which seems to solve the problem.
  # Note: there is no need to configure `gpg2` and `pass`, just install it.
  # See: https://stackoverflow.com/a/52251706
  apt:
    name:
      - gnupg2
      - pass
      #- dbus-x11
    state: present
  become: yes
  when: ansible_distribution_release == 'bionic'

- name: login target user into docker hub
  when: docker_hub_username != '' and docker_hub_password != ''
  block:
    - name: attempt to login into docker hub as user
      command:
        argv:
          - docker
          - login
          - --username={{ docker_hub_username }}
          - --password-stdin
        stdin: "{{ docker_hub_password }}"
        creates: ~/.docker/config.json

  rescue:
    # workaround for permission denied accessing docker socket

    - name: restart docker daemon to fix docker socket permission denied
      systemd:
        name: docker
        state: restarted
      become: yes

    - name: remove old docker hub token from root
      file:
        path: ~/.docker
        state: absent
      become: yes

    - name: attempt to login into docker hub as root
      command:
        argv:
          - docker
          - login
          - --username={{ docker_hub_username }}
          - --password-stdin
        stdin: "{{ docker_hub_password }}"
      become: yes

    - name: move docker hub token from root to login user
      shell: >
        chown -R {{ ansible_user_uid }}:{{ ansible_user_gid }} ~/.docker &&
        rm -rf "{{ ansible_user_dir }}/.docker" &&
        mv ~/.docker "{{ ansible_user_dir }}/"
      become: yes
  tags:
  - ip4only
...
