---
- name: add docker signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  register: add_docker_key_result
  until: add_docker_key_result is successful
  when: docker_from_docker_io |bool

- name: add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ codename }} stable"
    filename: docker-ce
  register: add_docker_repo_result
  until: add_docker_repo_result is successful
  when: docker_from_docker_io |bool
  vars:
    ## workaround for docker repo not yet ready on focal
    codename: "{{ 'eoan' if _codename == 'focal' and docker_focal_fix |bool else _codename }}"
    _codename: "{{ ansible_lsb.codename }}"

- block:
    - name: install docker and friends
      apt:
        name: "{{ packages_docker }},{{ packages_helpers }}"
        state: "{{ docker_upgrade |bool |ternary('latest', 'present') }}"
        autoremove: true
        install_recommends: false
  rescue:
    - name: install docker and friends (update apt cache)
      apt:
        name: "{{ packages_docker }},{{ packages_helpers }}"
        state: "{{ docker_upgrade |bool |ternary('latest', 'present') }}"
        autoremove: true
        install_recommends: false
        update_cache: true
  vars:
    packages_docker: "{{ docker_from_docker_io |bool |ternary(pkgs_dockerio, pkgs_ubuntu) }}"
    pkgs_ubuntu: docker.io,docker-compose
    pkgs_dockerio: docker-ce
    ## note: jq helps to parse docker output
    packages_helpers: jq,bash-completion,pigz

- name: bash completion script for docker
  file:
    src: /usr/share/bash-completion/completions/docker
    dest: /etc/bash_completion.d/docker
    state: link

- name: create new docker daemon settings
  copy:
    content: "{}"
    dest: /etc/docker/daemon.json
    force: false
    owner: root
    mode: 0644
  when: docker_daemon_settings |default({}) |length
  notify: restart docker daemon

- name: set custom docker daemon settings
  json_patch:
    src: /etc/docker/daemon.json
    operations:
      - op: add
        path: "{{ item.0 }}"
        value: "{{ item.1 }}"
    pretty: true
  loop: "{{ docker_daemon_settings |default({}) |dictsort }}"
  notify: restart docker daemon
  ## ansible lint raises error because json_patch module belongs with custom collection
  tags: skip_ansible_lint

- name: enable docker service
  systemd:
    name: docker
    state: started
    enabled: true
...
