---
- name: add target user in the docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: yes


- name: login target user into docker hub
  when: docker_hub_username != '' and docker_hub_password != ''
  block:
    - name: attempt to login into docker hub as user
      command:
        argv:
          - docker
          - login
          - --username={{ docker_hub_username }}
          - --password-stdin
        stdin: "{{ docker_hub_password }}"
        creates: ~/.docker/config.json

  rescue:
    # workaround for permission denied accessing docker socket

    - name: restart docker daemon to fix docker socket permission denied
      systemd:
        name: docker
        state: restarted
      become: yes

    - name: remove old docker hub token from root
      file:
        path: ~/.docker
        state: absent
      become: yes

    - name: attempt to login into docker hub as root
      command:
        argv:
          - docker
          - login
          - --username={{ docker_hub_username }}
          - --password-stdin
        stdin: "{{ docker_hub_password }}"
      become: yes

    - name: move docker hub token from root to login user
      shell: >
        chown -R {{ ansible_user_uid }}:{{ ansible_user_gid }} ~/.docker &&
        rm -rf "{{ ansible_user_dir }}/.docker" &&
        mv ~/.docker "{{ ansible_user_dir }}/"
      become: yes
...
