---
- name: uninstall stock docker-compose
  apt:
    name:
      - docker-compose
      # stock pyopenssl on xenial is incompoatible with docker-compose
      #- python-openssl
    state: absent

- name: detect latest docker-compose release
  uri:
    url: https://github.com/docker/compose/releases/latest
    method: HEAD
    creates: "{{ docker_allow_reinstall | bool
               | ternary(omit, docker_compose_binary_file) }}"
  #connection: local  # never use this with "creates"
  register: latest_dcomp_release
  when: docker_compose_release == 'latest'

- set_fact:
    docker_compose_release: "{{ latest_dcomp_release.url | basename }}"
  when: latest_dcomp_release is not skipped
        and latest_dcomp_release.url is defined

- debug:
    msg: "latest docker-compose release: {{ docker_compose_release }}"
  run_once: true
  when: latest_dcomp_release is not skipped
        and latest_dcomp_release.url is defined

- name: download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_release }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_binary_file }}"
    mode: 0755
    force: "{{ docker_allow_reinstall | bool }}"

- name: bash completion script for docker-compose (optional)
  block:
    - name: bash completion script for docker-compose (attempt to get release)
      get_url:
        url: https://raw.githubusercontent.com/docker/compose/{{ docker_compose_release }}/contrib/completion/bash/docker-compose
        dest: /etc/bash_completion.d/docker-compose
        mode: 0644
        force: "{{ docker_allow_reinstall | bool }}"
  rescue:
    - name: bash completion script for docker-compose (workaround, get master)
      get_url:
        url: https://raw.githubusercontent.com/docker/compose/master/contrib/completion/bash/docker-compose
        dest: /etc/bash_completion.d/docker-compose
        mode: 0644
        force: "{{ docker_allow_reinstall | bool }}"
  when: docker_bash_completion_extras | bool == true
  # end of block
...
