---
- name: install docker helpers
  block:
    - name: install docker helpers (rescue if it fails)
      apt:
        name: "{{ helpers }}"
  rescue:
    - name: install docker helpers (update cache)
      apt:
        name: "{{ helpers }}"
        update_cache: true
  vars:
    helpers:
      ## note: jq helps to parse docker output
      - jq
      - pigz
      - bash-completion
      # - criu  # criu install failed on hetzner-heron

- name: install extra docker tools
  apt:
    name:
      - bridge-utils
      - ipvsadm
      - apache2-utils
      - siege
  when: docker_extras |bool

- name: add docker signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  register: add_docker_key_result
  until: add_docker_key_result is successful
  when: docker_from_docker_io |bool

- name: add docker repository
  apt_repository:
    repo: "deb [arch={{ lin_apt_arch }}] {{ url }} {{ codename }} stable"
    filename: docker-ce
    mode: 0644
  register: add_docker_repo_result
  until: add_docker_repo_result is successful
  when: docker_from_docker_io |bool
  vars:
    url: https://download.docker.com/linux/ubuntu
    codename: "{{ ansible_lsb.codename }}"

- block:
    - name: install docker and friends
      apt:
        name: "{{ packages_docker }}"
        state: "{{ docker_upgrade |bool |ternary('latest', 'present') }}"
        autoremove: true
        install_recommends: false
  rescue:
    - name: install docker and friends (update apt cache)
      apt:
        name: "{{ packages_docker }}"
        state: "{{ docker_upgrade |bool |ternary('latest', 'present') }}"
        autoremove: true
        install_recommends: false
        update_cache: true
  vars:
    packages_docker: "{{ docker_from_docker_io |bool |ternary(pkgs_dockerio, pkgs_ubuntu) }}"
    pkgs_ubuntu: docker.io,docker-compose
    pkgs_dockerio: docker-ce


- name: bash completion script for docker
  file:
    src: /usr/share/bash-completion/completions/docker
    dest: /etc/bash_completion.d/docker
    state: link


- name: create directory for dockerd config
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: docker
    mode: 0750
  tags: [lin_docker_daemon, lin_docker_tls]

- name: configure docker daemon tls security
  import_tasks: tls.yml
  vars:
    _dockerd_ca_crt_from_vars: "{{ (docker_tls_ca_crt and docker_tls_ca_key) |ternary(true,false) }}"
    _dockerd_server_crt_from_vars: "{{ (docker_tls_server_crt and docker_tls_server_key) |ternary(true,false) }}"
  when: docker_tls_enable |bool
  tags: lin_docker_tls

- name: configure docker daemon
  import_tasks: daemon.yml
  tags: lin_docker_daemon

- name: configure docker engine logging
  import_tasks: syslog.yml
  when: docker_use_rsyslog |bool
  tags: lin_docker_syslog

- name: enable docker service
  systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: "{{ _docker_systemd_dropin |d({}) is changed }}"
  tags: lin_docker_daemon
...
