---
- name: detect latest docker-machine release
  github_release:
    repository: docker/machine
    release: "{{ docker_machine_release }}"
    template: "{download_url}/docker-machine-Linux-x86_64"
    creates: "{{ docker_machine_binary_file }}"
    reinstall: "{{ docker_upgrade |bool }}"
  tags: skip_ansible_lint
  register: latest_dman_release

- name: download docker-machine
  get_url:
    url: "{{ latest_dman_release.url }}"
    dest: "{{ docker_machine_binary_file }}"
    mode: 0755
    force: "{{ docker_upgrade |bool }}"
  when: latest_dman_release is changed
  ## fix intermittent network failures
  register: download_result
  until: download_result.msg |d('') is not search('timed out')

- name: bash completion scripts for docker-machine (optional, so ok to fail)
  get_url:
    url: https://raw.githubusercontent.com/docker/machine/master/contrib/completion/bash/{{ item }}.bash
    dest: /etc/bash_completion.d/{{ item }}
    mode: 0644
    force: "{{ docker_upgrade |bool }}"
  loop:
    - docker-machine
    - docker-machine-prompt
    - docker-machine-wrapper
  ## stuff of low importance, so ok to fail
  failed_when: false
  when:
    - docker_bash_completion_extras |bool
    - not ansible_check_mode  # avoid false change result from get_url
...
