---
# tasks for ivansible.lin_docker

- name: install docker core
  import_tasks: docker-core.yml
  become: true
  tags:
    - lin_docker_core
    - lin_docker_all

- name: install ansible docker bindings
  apt:
    name:
      - python-docker
      - python3-docker
  become: true
  tags:
    - lin_docker_ansible
    - lin_docker_all

- name: install docker-compose
  import_tasks: docker-compose.yml
  when: docker_compose_enable |bool
  become: true
  tags:
    - lin_docker_compose
    - lin_docker_all
    - ip4only

- name: install docker machine
  import_tasks: docker-machine.yml
  when: docker_extras |bool and docker_machine_enable |bool
  become: true
  tags:
    - lin_docker_machine
    - lin_docker_all
    - ip4only

- name: create docker-enabled group
  group:
    name: docker
    state: present
  become: true
  tags:
    - lin_docker_all

- name: checkout docker files, if permitted
  git:
    dest: "{{ docker_files_dir }}"
    repo: "{{ docker_files_repo }}"
    version: "{{ docker_files_branch }}"
    # only clone, don't choke on pending modifications
    update: false
    accept_hostkey: true
  when: is_permitted |bool and docker_files_repo != ''  # noqa 602
  tags:
    - lin_docker_files
    - lin_docker_all

- name: give target user permissions for docker group/hub
  import_tasks: docker-user.yml
  when: docker_permit_user |bool and is_permitted |bool
  tags:
    - lin_docker_user
    - lin_docker_all
...
