---
# tasks file for ivansible.lin_docker

- setup:

- name: install docker core
  import_tasks: docker-core.yml
  become: yes
  tags:
  - lin_docker_core
  - lin_docker

- name: install ansible docker bindings
  apt:
    name: "{{ ansible_python_version.startswith('3') | ternary('python3','python') }}-docker"
  become: yes
  tags:
  - lin_docker_ansible
  - lin_docker

- name: install docker-compose
  import_tasks: docker-compose.yml
  become: yes
  tags:
  - lin_docker_compose
  - lin_docker
  - ip4only

- name: install docker machine
  import_tasks: docker-machine.yml
  when: docker_extras | bool == true
  become: yes
  tags:
  - lin_docker_machine
  - lin_docker
  - ip4only

- name: create docker-enabled group
  group:
    name: docker
    state: present
  become: yes
  tags:
  - lin_docker

- name: give target user permissions for docker group/hub
  import_tasks: docker-user.yml
  when: docker_permit_user | bool == true
  tags:
  - lin_docker_user
  - lin_docker
...
