---
- name: install docker engine
  import_tasks: engine.yml
  tags: lin_docker_engine


- name: install ansible docker bindings
  apt:
    name: "{{ lin_use_python2 |bool |ternary(packages_pythons, packages_python3) }}"
  vars:
    packages_pythons: python3-docker,python-docker
    packages_python3: python3-docker
  tags: lin_docker_ansible

- name: upgrade python sdk for new swarm features
  pip:
    name: docker>4
    executable: "{{ item }}"
  loop: "{{ lin_use_python2 |bool |ternary(['pip','pip3'], ['pip3']) }}"
  when:
    - _swarm_role == 'manager_master'
    - docker_swarm_overlay_pool4 |d('')
  tags: lin_docker_ansible


- name: install docker-compose from github
  import_tasks: compose.yml
  when: docker_compose_github_enable |bool
  tags: [lin_docker_compose, ip4only]

- name: install docker machine from github
  import_tasks: machine.yml
  when:
    - docker_machine_github_enable |bool
    - docker_extras |bool
  tags: [lin_docker_machine, ip4only]


- name: configure gwbridge network
  import_tasks: gwbridge.yml
  when: docker_gwbridge_addr4 |d('')
  tags: lin_docker_gwbridge

- name: configure docker swarm
  import_tasks: swarm.yml
  when: _swarm_role != 'none'
  tags: lin_docker_swarm


- name: enable daily docker garbage collector
  copy:
    dest: /etc/cron.daily/docker-gc
    content: |
      #!/bin/sh
      {{ comment }}docker system prune --force --all |grep -v 'reclaimed space: 0B' ||:
    mode: 0755
    force: true
  vars:
    comment: "{{ docker_daily_gc |bool |ternary('','#') }}"
  notify: reload systemd daemon

- name: create docker-enabled group
  group:
    name: docker
    state: present
...
