---
## fix python cryptography and openssl on xenial

- name: upgrade python{{ ver }} cryptography package
  pip:
    ## only cryptography v2.9 has sane wheels for both python 2 and 3 on xenial
    name: cryptography == 2.9
    executable: "pip{{ ver }}"

- name: fix broken ansible to python{{ ver }}-openssl bindings on xenial
  block:
    - name: verify validity of python{{ ver }}-openssl packages (ok to fail, will rescue)
      command: "python{{ ver }} -c 'from OpenSSL import SSL'"
      changed_when: false
      ## minimize long error message
      no_log: "{{ hide_secrets |bool }}"
  rescue:
    - name: upgrade python{{ ver }}-openssl apt package
      apt:
        ## noqa 403
        name: python{{ ver }}-openssl
        state: latest
        update_cache: true
      ignore_errors: true
      no_log: "{{ hide_secrets |bool }}"

    ## https://stackoverflow.com/questions/45188413/python-pip-install-is-failing-with-attributeerror-module-object-has-no-att
    - name: upgrade python{{ ver }}-openssl python package
      ## easy_install is part of python-setuptools
      ## mitigate pyOpenSSL 20.0+ failure to install on xenial
      command: python{{ ver }} -m easy_install --upgrade "pyOpenSSL<20"
...
