---
- name: disable motd banners on ubuntu xenial
  include_tasks: motd-xenial.yml
  args:
    apply:
      become: true
      tags:
        - lin_motd_xenial
        - lin_motd_all
  when: ansible_lsb.codename in ['xenial']
  tags:
    - lin_motd_xenial
    - lin_motd_all

- name: disable motd banners on ubuntu bionic+
  include_tasks: motd-bionic.yml
  args:
    apply:
      become: true
      tags:
        - lin_motd_bionic
        - lin_motd_all
  when: ansible_lsb.release is version('18.04','>=')
  tags:
    - lin_motd_bionic
    - lin_motd_all
...
