---
- name: install docker as root
  ansible.builtin.import_tasks: root.yml
  when: lin_use_docker |d(true) |bool  # inherited from lin_base
  become: true
  vars:
    _swarm_role: "{{ docker_swarm_role |d('none',true) |replace('-','_') }}"
  tags: [lin_docker_all]


- name: check whether user has custom bashrc
  ansible.builtin.stat:
    path: ~/.local/bashrc
  register: _user_local_bashrc
  tags: [lin_docker_bashrc, lin_docker_all]

- name: user bash addons for docker cli (optional)
  ansible.builtin.import_tasks: bashrc.yml
  when: _user_local_bashrc.stat.exists
  tags: [lin_docker_bashrc, lin_docker_all]


- name: give target user permissions for docker group/hub
  ansible.builtin.import_tasks: user.yml
  when: docker_permit_user |bool
  tags: [lin_docker_user, lin_docker_all]


- name: checkout docker files, if permitted
  ansible.builtin.git:
    dest: "{{ docker_files_dir }}"
    repo: "{{ docker_files_repo }}"
    version: "{{ docker_files_branch }}"
    ## only clone, don't choke on pending modifications
    update: false
    accept_hostkey: true
  when:
    - docker_files_repo |default('')
    - is_permitted |bool
  tags: [lin_docker_files, lin_docker_all]


- name: apply postponed changes
  ansible.builtin.meta: flush_handlers
...
