---
## reset_connection is wrapped in an included task to avoid ansible warning
## "reset_connection task does not support when conditional"
- name: connection reset will apply new group to the ansible session
  ansible.builtin.meta: reset_connection
...
