---
- name: create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: install docker engine
  ansible.builtin.import_tasks: engine.yml
  tags: lin_docker_engine


- name: install ansible docker bindings
  ansible.builtin.import_tasks: ansible-docker.yml
  tags: lin_docker_ansible


- name: install docker-compose from github
  ansible.builtin.import_tasks: compose.yml
  when: docker_compose_github_enable |bool
  tags: [lin_docker_compose, ip4only]

- name: install docker machine from github
  ansible.builtin.import_tasks: machine.yml
  when:
    - docker_machine_github_enable |bool
    - docker_extras |bool
  tags: [lin_docker_machine, ip4only]


- name: apply dockerd changes before poking swarm
  ansible.builtin.meta: flush_handlers

- name: reset swarm
  community.docker.docker_swarm:
    state: absent
    force: true
  when: docker_swarm_reset |bool
     or docker_swarm_destroy |bool
  tags:
    - lin_docker_swarm
    - lin_docker_swarm_reset
    - lin_docker_reset

- name: configure gwbridge network
  ansible.builtin.import_tasks: gwbridge.yml
  when:
    - docker_gwbridge_addr4 |d('')
    - not docker_swarm_destroy |bool
  tags: lin_docker_gwbridge

- name: configure docker swarm
  ansible.builtin.import_tasks: swarm.yml
  when:
    - _swarm_role != 'none'
    - not docker_swarm_destroy |bool
  tags: lin_docker_swarm


- name: fix race between dockerd and udevd for gwbridge
  ## https://github.com/systemd/systemd/issues/3374#issuecomment-452718898
  ## dockerd creates the bridge and then sets it address, this races
  ## with udev and results in the following message in system log:
  ## "udevd: could not generate persistent MAC address"
  ## the fix prevents systemd (udevd or networkd) from tinkering
  ## with MAC of virtual network devices, namely docker gwbridge
  ansible.builtin.copy:
    dest: /etc/systemd/network/99-default.link
    content: |
      # prevent error "could not generate persistent MAC address"
      # due to race between dockerd and udevd for gwbridge

      [Match]
      Path=/devices/virtual/net/*

      [Link]
      NamePolicy=kernel database onboard slot path
      MACAddressPolicy=none
    mode: 0644
  notify: reload systemd daemon
  when: ansible_lsb.release is version('20.04','<')
  tags: lin_docker_gwbridge


- name: enable daily docker garbage collector
  ansible.builtin.copy:
    dest: /etc/cron.daily/docker-gc
    content: |
      #!/bin/sh
      {{ comment }}export HOME=/root
      {{ comment }}docker system prune --force --all |grep -v 'reclaimed space: 0B' ||:
    mode: 0755
    force: true
  vars:
    comment: "{{ docker_daily_gc |bool |ternary('','#') }}"
  when: docker_daily_gc is not none
  notify: reload systemd daemon
  tags: lin_docker_helpers

- name: enable daily container updater
  ansible.builtin.import_tasks: watchtower.yml
  vars:
    _watchtower_enable: "{{ docker_watchtower_enable |bool }}"
  when: docker_watchtower_enable is not none
  tags: lin_docker_helpers
...
