---
- name: directory for ferm configuration
  file:
    path: "{{ ferm_dir }}/{{ item }}"
    state: directory
  loop:
    - ""
    - parts
    - input
    - forward
    - before
    - after

- name: create ferm configuration
  template:
    src: "{{ item }}"
    dest: "{{ ferm_dir }}/{{ item }}"
  loop: "{{ ferm_configs }}"
  notify: restart ferm service

- name: create ferm port/host lists
  copy:
    dest: "{{ ferm_dir }}/{{ item }}"
    content: |
      # ferm {{ item }}
      # ansible-managed
    force: false
  loop: "{{ ferm_lists }}"
  notify: restart ferm service

- name: set permissions of ferm config files
  file:
    path: "{{ ferm_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0640
  with_flattened:
    - "{{ ferm_configs }}"
    - "{{ ferm_lists }}"

- name: open external ports in ferm before first start
  lineinfile:
    path: "{{ ferm_dir }}/ports.ext"
    line: "{{ item |string }}"
  loop: "{{ ferm_ports_external }}"
  notify: restart ferm service
...
