---
- name: remove stock ferm
  apt:
    name: ferm
    state: absent
    purge: true

- name: install perl Net::DNS and ipset packages
  apt:
    name:
      - libnet-dns-perl
      - ipset
      - iptables
      ## install gcc to build 'no-lock' library
      - build-essential
    state: present

- name: download ferm script (skip in check mode)
  get_url:
    url: "{{ ferm_script_url }}"
    dest: "{{ ferm_binary }}"
    owner: root
    group: root
    mode: 0754
    force: "{{ ferm_upgrade |bool }}"
  notify: reload ferm service
  ## this task always reports as changed in check mode
  when: not ansible_check_mode

- name: upload ferm helper scripts
  template:
    src: "bin/{{ item }}"
    dest: "{{ ferm_bindir }}/{{ item |splitext |first }}"
    owner: root
    group: root
    mode: 0754
  loop:
    - ferm-ipset.pl
    - ferm-openvz.pl
    - ferm-ctl.py
  notify: reload ferm service

- name: build ferm helper library
  command:
    cmd: gcc -shared "-Wl,-soname,{{ ferm_lib_nolock |basename }}.so" -o "{{ ferm_lib_nolock }}" -fPIC -lc -xc -
    stdin: "int flock(int fd, int op) { return 0; }"
    creates: "{{ ferm_lib_nolock }}"
...
