---
- name: remove stock ferm
  apt:
    name: ferm
    state: absent
    purge: true

- name: install perl Net::DNS and ipset packages
  apt:
    name:
      - libnet-dns-perl
      - ipset
      - iptables
    state: present

- name: download ferm script
  get_url:
    url: "{{ ferm_script_url }}"
    dest: "{{ ferm_binary }}"
    owner: root
    group: root
    mode: 0755
    force: "{{ ferm_allow_reinstall |bool }}"
  notify: reload ferm service

- name: upload ferm ipset/openvz scripts
  template:
    src: "{{ item }}.pl"
    dest: "{{ ferm_bindir }}/{{ item }}"
    owner: root
    group: root
    mode: 0754
  loop:
    - ferm-ipset
    - ferm-openvz
  notify: reload ferm service
...
