---
- name: remove stock ferm
  apt:
    name: ferm
    state: absent

- name: install perl Net::DNS and ipset packages
  apt:
    name:
      - libnet-dns-perl
      - ipset
      - iptables
    state: present

- name: download ferm script
  get_url:
    url: "{{ ferm_script_url }}"
    dest: "{{ ferm_binary }}"
    owner: root
    group: root
    mode: 0755
    force: "{{ ferm_allow_reinstall |bool }}"
  notify: reload ferm service

- name: upload ferm ipset script
  template:
    src: ferm-ipset
    dest: "{{ ferm_ipset_binary }}"
    owner: root
    group: root
    mode: 0755
  notify: reload ferm service
...
