---
- name: install ferm
  import_tasks: install.yml
  tags: lin_ferm_install

- name: configure ferm
  import_tasks: config.yml
  tags: lin_ferm_config

- name: run ferm service
  import_tasks: service.yml
  tags: lin_ferm_service
...
