---
- name: setup ferm service
  template:
    src: etc/ferm.service
    dest: /etc/systemd/system/ferm.service
  register: ferm_service_result
  notify: reload ferm service

- name: reload ferm service config in systemd
  command: systemctl daemon-reload  # noqa 303
  when: ferm_service_result is changed

- name: disable ufw (please ignore possible failure)
  ufw:
    state: disabled
  no_log: "{{ hide_secrets |bool }}"
  ignore_errors: true

- name: activate ferm
  systemd:
    name: ferm
    state: started
    enabled: true
...
