---
- name: restic environment variables for cron
  blockinfile:
    dest: /etc/default/restic
    content: |
      RESTIC_REPOSITORY={{ lin_restic_repository }}
      RESTIC_PASSWORD={{ lin_restic_password }}
      RCLONE_CONFIG={{ lin_rclone_config }}
      {% for key, val in lin_restic_cmd_vars |dictsort %}
      {{ key }}={{ val }}
      {% endfor %}
    marker: '# RESTIC {mark}'
    owner: root
    group: rclone
    mode: 0640
    create: true
  no_log: "{{ hide_secrets |bool }}"


- name: validate restic backup jobs
  assert:
    that:
      - item.name is defined
      - item.type in ['filesystem', 'postgres', 'command']
    quiet: true
  loop: "{{ lin_restic_jobs }}"

- name: generate restic backup script
  template:
    src: restic-backup.sh.j2
    dest: /etc/systemd/system/restic-backup.sh
    owner: restic
    group: rclone
    mode: 0750
  register: restic_backup_script_result
  vars:
    verb_opts: "{{ ['--verbose=%s' |format(lin_restic_cron_verbose)]
                   if lin_restic_cron_verbose |int > 0 else [] }}"
  notify: reload systemd daemon

- name: setup restic backup service
  copy:
    dest: /etc/systemd/system/restic-backup.service
    content: |
      # ansible-managed
      [Unit]
      Description=Restic backup
      [Service]
      Type=oneshot
      User=restic
      Group=rclone
      EnvironmentFile=/etc/default/restic
      ExecStart=/etc/systemd/system/restic-backup.sh
    force: true
  register: restic_backup_service_result
  notify: reload systemd daemon

- name: configure restic backup timer
  copy:
    dest: /etc/systemd/system/restic-backup.timer
    content: |
      # ansible-managed
      [Unit]
      Description=Restic backup
      [Timer]
      OnCalendar={{ lin_restic_cron_time_backup }}
      [Install]
      WantedBy=timers.target
    force: true
  register: restic_backup_timer_result
  notify: reload systemd daemon

- name: activate restic daily backup job
  systemd:
    name: restic-backup.timer
    state: started
    enabled: true
    daemon_reload: "{{ script_changed or service_changed or timer_changed }}"
  vars:
    script_changed: "{{ restic_backup_script_result is changed }}"
    service_changed: "{{ restic_backup_service_result is changed }}"
    timer_changed: "{{ restic_backup_timer_result is changed }}"


- name: generate restic weekly prune script
  template:
    src: restic-prune.sh.j2
    dest: /etc/systemd/system/restic-prune.sh
    owner: restic
    group: rclone
    mode: 0750
  vars:
    verb_opts: "{{ ('--verbose=%s ' % lin_restic_cron_verbose)
                   if (lin_restic_cron_verbose |int > 0) else '' }}"
    forget_opts: >-
      --keep-last={{ lin_restic_forget_keep_last }}
      --keep-daily={{ lin_restic_forget_keep_daily }}
      --keep-weekly={{ lin_restic_forget_keep_weekly }}
      --keep-monthly={{ lin_restic_forget_keep_monthly }}
      --keep-yearly={{ lin_restic_forget_keep_yearly }}
  register: restic_prune_script_result
  notify: reload systemd daemon

- name: setup restic weekly prune service
  copy:
    dest: /etc/systemd/system/restic-prune.service
    content: |
      # ansible-managed
      [Unit]
      Description=Restic prune
      {% if lin_restic_cron_ordering |bool %}
      After=restic-backup.service
      {% endif %}
      [Service]
      Type=oneshot
      User=restic
      Group=rclone
      EnvironmentFile=/etc/default/restic
      ExecStart=/etc/systemd/system/restic-prune.sh
    force: true
  register: restic_prune_service_result
  notify: reload systemd daemon

- name: configure restic weekly prune timer
  copy:
    dest: /etc/systemd/system/restic-prune.timer
    content: |
      # ansible-managed
      [Unit]
      Description=Restic prune
      [Timer]
      OnCalendar={{ day }} {{ time }}
      [Install]
      WantedBy=timers.target
    force: true
  register: restic_prune_timer_result
  notify: reload systemd daemon
  vars:
    day: "{{ lin_restic_cron_day_prune |default('Mon', true) }}"
    time: "{{ lin_restic_cron_time_prune |default('5:00', true) }}"

- name: (de)activate restic weekly prune job
  systemd:
    name: restic-prune.timer
    state: "{{ active |ternary('started', 'stopped') }}"
    enabled: "{{ active }}"
    daemon_reload: "{{ script_changed or service_changed or timer_changed }}"
  vars:
    day: "{{ lin_restic_cron_day_prune |default('',true) }}"
    time: "{{ lin_restic_cron_time_prune |default('',true) }}"
    active: "{{ true if day and time else false }}"

    script_changed: "{{ restic_prune_script_result is changed }}"
    service_changed: "{{ restic_prune_service_result is changed }}"
    timer_changed: "{{ restic_prune_timer_result is changed }}"
...
