---
- name: install system packages for backup
  apt:
    name: "{{ lin_restic_packages }}"
    state: present

- name: detect latest restic release
  github_release:
    repository: restic
    release: "{{ lin_restic_version }}"
    owner: "{{ lin_restic_repo_owner }}"
    template: '{download_url}/restic_{ver}_linux_amd64.bz2'
    strip_v: true
    creates: "{{ lin_restic_binary }}"
    reinstall: "{{ lin_restic_upgrade |bool }}"
  register: _restic_release

- name: download compressed restic binary
  get_url:
    url: "{{ _restic_release.url }}"
    dest: "{{ lin_restic_binary }}.bz2"
    force: true
  when: _restic_release is changed

- name: uncompress restic binary
  command: bunzip2 -f "{{ lin_restic_binary }}.bz2"
  when: _restic_release is changed

- name: ensure permissions of restic binary
  file:
    path: "{{ lin_restic_binary }}"
    owner: root
    group: rclone
    mode: 0750
  ignore_errors: "{{ ansible_check_mode |bool }}"
  register: _restic_binary_mode

- name: add full backup capabilities to restic binary
  ## https://restic.readthedocs.io/en/stable/080_examples.html#full-backup-without-root
  capabilities:
    path: "{{ lin_restic_binary }}"
    capability: cap_dac_read_search=+ep
    state: present
  ignore_errors: "{{ ansible_check_mode |bool }}"
  ## workaround for buggy setcap, which is always "changed"
  when: _restic_release is changed
        or _restic_binary_mode is changed

- name: generate restic bash completion
  command: >
    "{{ lin_restic_binary }}" generate --bash-completion "{{ completion_script }}"
  args:
    creates: "{{ completion_script }}"
  vars:
    completion_script: /etc/bash_completion.d/restic
...
