---
- name: install system packages for backup
  apt:
    name: "{{ lin_restic_packages }}"
    state: present

- name: install restic binary
  block:
    - name: detect latest restic binary release
      github_release:
        repository: restic
        release: "{{ lin_restic_version }}"
        owner: "{{ lin_restic_repo_owner }}"
        template: '{download_url}/restic_{ver}_linux_amd64.bz2'
        strip_v: true
        version_script: "{{ lin_restic_binary }} version"
        script_regex: '[0-9][.][0-9.a-z_-]+'
        reinstall: "{{ lin_restic_upgrade |bool }}"
      register: _restic_release

    - name: download compressed restic binary
      get_url:
        url: "{{ _restic_release.url }}"
        dest: "{{ lin_restic_binary }}.bz2"
        force: true
      when: _restic_release is changed

    - name: uncompress restic binary
      command: bunzip2 -f "{{ lin_restic_binary }}.bz2"
      when: _restic_release is changed
  when: not lin_restic_from_zip |bool

- name: install restic binary from zip archive
  block:
    - name: detect latest restic archive release
      github_release:
        repository: restic
        release: "{{ lin_restic_version }}"
        owner: "{{ lin_restic_repo_owner }}"
        template: '{download_url}/restic_{ver}_linux_amd64.zip'
        strip_v: true
        version_script: "{{ lin_restic_binary }} version"
        script_regex: '[0-9][.][0-9.a-zA-Z_-]+'
        reinstall: "{{ lin_restic_upgrade |bool }}"
      register: _restic_release

    - name: download and install restic zip archive
      unarchive:
        remote_src: true
        src: "{{ _restic_release.url }}"
        dest: "{{ lin_restic_binary |dirname }}"
        exclude:
          - CHANGELOG.md
          - LICENSE
          - README.rst
      when: _restic_release is changed
  when: lin_restic_from_zip |bool

- name: ensure permissions of restic binary
  file:
    path: "{{ lin_restic_binary }}"
    owner: root
    group: rclone
    mode: 0750
  ignore_errors: "{{ ansible_check_mode |bool }}"
  register: _restic_binary_mode

- name: add full backup capabilities to restic binary
  ## https://restic.readthedocs.io/en/stable/080_examples.html#full-backup-without-root
  capabilities:
    path: "{{ lin_restic_binary }}"
    capability: cap_dac_read_search=+ep
    state: present
  register: _restic_binary_caps
  failed_when:
    - _restic_binary_caps is failed
    - not ansible_check_mode
  ## workaround for buggy setcap, which is always "changed"
  when: _restic_release is changed
     or _restic_binary_mode is changed

- name: generate restic bash completion
  command: >
    "{{ lin_restic_binary }}" generate --bash-completion "{{ completion_script }}"
  args:
    creates: "{{ completion_script }}"
  vars:
    completion_script: /etc/bash_completion.d/restic
...
