---
all:
  children:
    molecule:
      vars:
        is_permitted: false
        lin_core_system_locale: en_US.UTF-8
        allow_sysctl: false
        lin_firewall: none  # no mucking iptables on github runners nor in docker
        lin_use_ssh: false  # ssh is handled by another role, skip the test
        real_ssh_port: 0
      children:
        docker_molecule:
          vars:
            ansible_user: ansible
            lin_core_time_sync: false
        local_molecule:
          vars:
            lin_core_time_sync: true
...
