---
- name: add ansible ppa
  apt_repository:
    repo: ppa:ansible/ansible
    filename: ansible
  become: yes

- name: install ansible from ppa
  apt:
    name:
      - python-pip
      - virtualenv
      - ansible
  become: yes

# stock python-pywinrm does not provide ntlm
# required by ssl winrm transport
# probably bionic pywinrm is fine
- name: upgrade pywinrm module
  pip:
    name: pywinrm
  become: yes
...
