---
- name: install wireguard as root
  ansible.builtin.import_tasks: root.yml
  become: true
  when: lin_wg_nets |d([])
  tags:
    - lin_wg_all
    - lin_wireguard_all

- name: run wireguard handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - lin_wg_all
    - lin_wireguard_all
...
