---
all:
  children:
    molecule:
      children:
        docker_molecule:
        local_molecule:
      vars:
        ansible_user: ansible
        is_permitted: false
        allow_sysctl: false
        lin_use_ssh: false
        lin_firewall: none
        lin_core_time_sync: false
        lin_core_system_locale: en_US.UTF-8
...
