---
## handlers for ivansible.lin_yggdrasil

- name: restart yggdrasil service
  ansible.builtin.systemd:
    name: yggdrasil
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
...
